SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[Kristy_Internal_LP_Prices] as

select WWS.NEW, WWS.YS, BI.CODENO, WWS.REGNAME, WWS.CODENAME, WWS.D,  HP.NEWCOST, HP.NEWSELL, CAST(((HP.NEWSELL-HP.NEWCOST)/HP.NEWSELL)*100 AS DECIMAL(4,1)) AS GP,
HP.COMMENT,  WWS.HOUSED, BI.EC, WWS.DOB, WWS.UDT, HPSXD.NEWCOST AS X_NEWCOST, HPSXD.NEWSELL AS X_NEWSELL, CAST(((HPSXD.NEWSELL - HPSXD.NEWCOST)/HPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP, 
HPSXD.COMMENT AS X_COMMENT, 
BI2.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN HPRICE HP ON HP.CODENO = BI.CODENO LEFT JOIN BULLINDEX BI2 ON BI.UID = BI2.UID AND 
BI2.STYPE = 'X' and BI2.CODENO NOT LIKE '514%' LEFT OUTER JOIN HSXDPRICE HPSXD ON BI2.CODENO = HPSXD.CODENO WHERE BI.STYPE = 'C' AND BI.LP <> 0 

UNION ALL SELECT WWS.NEW, WWS.YS, BI.CODENO, WWS.REGNAME, WWS.CODENAME, WWS.D, NULL as NEWCOST, NULL AS NEWSELL, NULL AS GP, NULL AS COMMENT, WWS.HOUSED, NULL AS EC,
 WWS.DOB, WWS.UDT, HPSXD.NEWCOST AS X_NEWCOST, HPSXD.NEWSELL AS X_NEWSELL, CAST(((HPSXD.NEWSELL - HPSXD.NEWCOST)/HPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP,
HPSXD.COMMENT AS X_COMMENT, BI.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN HSXDPRICE HPSXD ON BI.CODENO = HPSXD.CODENO
WHERE WWS.SEXED_ONLY <> 0 AND BI.LP <> 0 AND BI.CODENO NOT LIKE ('514%')

UNION ALL SELECT WWS.NEW, WWS.YS,  BI.CODENO, WWS.REGNAME, WWS.CODENAME, WWS.D,  CP.NEWCOST, CP.NEWSELL, CAST(((CP.NEWSELL-CP.NEWCOST)/CP.NEWSELL)*100 AS DECIMAL(4,1)) AS GP,
CP.COMMENT, WWS.HOUSED, BI.EC, WWS.DOB, WWS.UDT, CPSXD.NEWCOST AS X_NEWCOST, CPSXD.NEWSELL AS X_NEWSELL, 
CAST(((CPSXD.NEWSELL - CPSXD.NEWCOST)/CPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP, CPSXD.COMMENT AS X_COMMENT, BI2.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN CPRICE CP ON CP.CODENO = BI.CODENO LEFT JOIN BULLINDEX BI2 ON BI.UID = BI2.UID AND 
BI2.STYPE = 'X' LEFT OUTER JOIN HSXDPRICE CPSXD ON BI2.CODENO = CPSXD.CODENO WHERE BI.STYPE = 'C' AND BI.LP <> 0 

UNION ALL SELECT WWS.NEW, WWS.YS, BI.CODENO, WWS.REGNAME, WWS.CODENAME, WWS.D, NULL as NEWCOST, NULL AS NEWSELL, NULL AS GP, NULL AS COMMENT, WWS.HOUSED, NULL AS EC,
WWS.DOB, WWS.UDT, CPSXD.NEWCOST AS X_NEWCOST, CPSXD.NEWSELL AS X_NEWSELL, CAST(((CPSXD.NEWSELL - CPSXD.NEWCOST)/CPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP,
CPSXD.COMMENT AS X_COMMENT, BI.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN CSXDPRICE CPSXD ON BI.CODENO = CPSXD.CODENO
WHERE WWS.SEXED_ONLY <> 0 AND BI.LP <> 0  
GO