SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[HOLSTEINQUERY]
AS
     SELECT BI2.ACTIVE AS ACTIVE,
            BI2.DEL AS DEL,
            WWS.NEW AS NEW,
            WWS.YS AS YS,
            WWS.UID AS UID,
            WWS.REGNAME AS REGNAME,
            WWS.RECESS AS RECESS,
            WWS.D AS D,
            WWS.CODENAME AS CODENAME,
            BI2.CODENO AS CODENO,
            WWS.BREED AS BREED,
            WWS.COUNTRY AS COUNTRY,
            WWS.IDNO AS IDNO,
            WWS.STUD AS STUD,
            WWS.LOCATION AS LOCATION,
            WWS.DOB AS DOB,
            MD.SOURCE AS SOURCE,
            MD.NDTRS AS NDTRS,
            MD.NHRDS AS NHRDS,
            MD.PTAM AS PTAM,
            MD.PTAF_P AS PTAF_P,
            MD.PTAF AS PTAF,
            MD.PTAP_P AS PTAP_P,
            MD.PTAP AS PTAP,
            MD.REL_YLD AS REL_YLD,
            MD.REL_MF AS REL_MF,
            MD.PREL AS PREL,
            MD.NM AS NM,
            MD.REL_NM AS REL_NM,
            MD.PL AS PL,
            MD.REL_PL AS REL_PL,
            MD.SCS AS SCS,
            MD.REL_SCS AS REL_SCS,
            MD.DPR AS DPR,
            MD.REL_DPR AS REL_DPR,
            MD.MILK AS MILK,
            MD.FAT_P AS FAT_P,
            MD.FAT AS FAT,
            MD.PROTM AS PROTM,
            MD.PRO_P AS PRO_P,
            MD.PRO AS PRO,
            MD.NM_PCTILE AS NM_PCTILE,
            MD.TPI AS TPI,
            MD.TSOURCE AS TSOURCE,
            MD.TDATE AS TDATE,
            MD.TDTRS AS TDTRS,
            MD.THRDS AS THRDS,
            MD.PTAT AS PTAT,
            MD.TREL AS TREL,
            MD.UDC AS UDC,
            MD.FLC AS FLC,
            MD.BDC AS BWC,
            MD.DC AS DC,
            MD.LDTRS AS LDTRS,
            MD.LHRDS AS LHRDS,
            MD.STAT AS STAT,
            MD.Str AS STR,
            MD.BD AS BD,
            MD.DF AS DF,
            MD.RA AS RA,
            MD.THURLW AS THURLW,
            MD.RLS AS RLS,
            MD.RLR AS RLR,
            MD.FA AS FA,
            MD.FLS AS FLS,
            MD.FUA AS FUA,
            MD.RUH AS RUH,
            MD.RUW AS RUW,
            MD.UC AS UC,
            MD.UD AS UD,
            MD.FTP AS FTP,
            MD.RTP AS RTP,
            MD.TEATL AS TEATL,
            MD.CEDATE AS CEDATE,
            MD.SCE AS SCE,
            MD.PRELIM AS PRELIM,
            MD.SCE_OBS AS SCE_OBS,
            MD.SCE_REL AS SCE_REL,
            MD.DCE AS DCE,
            MD.DCE_OBS AS DCE_OBS,
            MD.DCE_REL AS DCE_REL,
            MD.SSB_PCT AS SSB_PCT,
            MD.SSB_OBS AS SSB_OBS,
            MD.SSB_REL AS SSB_REL,
            MD.SSB_SOURCE AS SSB_SOURCE,
            MD.SSB_OFF AS SSB_OFF,
            MD.DSB_PCT AS DSB_PCT,
            MD.DSB_OBS AS DSB_OBS,
            MD.DSB_REL AS DSB_REL,
            MD.MS AS MS,
            MD.DIS AS DIS,
            CASE
                WHEN MD.SERV_SCR IS NULL
                THEN 'N/A'
                WHEN MD.SCR = 0
                THEN '0.0'
                ELSE CAST(ROUND(MD.SCR, 1) AS VARCHAR(5))
            END AS SCR,
            CASE
                WHEN MD.SERV_SCR IS NULL
                THEN 'N/A'
                ELSE CAST(MD.SERV_SCR AS VARCHAR(6))
            END AS SERV_SCR,
            CASE
                WHEN MD.SERV_SCR IS NULL
                THEN 'N/A'
                ELSE CAST(MD.REL_SCR AS VARCHAR(5))
            END AS REL_SCR,
            MD.EVALDATE AS EVALDATE,
            MD.SREGNAME AS SREGNAME,
            MD.SIDNO AS SIDNO,
            MD.SBREED AS SBREED,
            MD.SCOUNTRY AS SCOUNTRY,
            MD.DREGNAME AS DREGNAME,
            MD.HBSTATUS AS HBSTATUS,
            MD.RHAIND AS RHAIND,
            WWS.BREEDSORT AS BREEDSORT,
            BI2.QUAL AS QUAL,
            BI2.CONC AS CONC,
            WWS.KC AS KC,
            WWS.BLG AS BLG,
            WWS.BCN AS BCN,
            WWS.IBR AS IBR,
            WWS.LEU AS LEU,
            WWS.BT AS BT,
            WWS.EHD AS EHD,
            WWS.JOHNES AS JOHNES,
            BI2.EC AS EC,
            ec.ECSTATUS AS ECSTATUS,
            ec.QUALIFIED AS QUALIFIED,
            BI2.HCOMMENT AS HCOMMENT,
            WWS.PEDIGREE AS PEDIGREE,
            WWS.BLACK_PCT AS BLACK_PCT,
            WWS.AAA AS AAA,
            WWS.DMS AS DMS,
            WWS.SAUDI AS SAUDI,
            WWS.UKLIST AS UKLIST,
            WWS.IRAN AS IRAN,
            WWS.Russia AS Russia,
            WWS.RSA AS RSA,
            WWS.ITALYLIST AS ITALYLIST,
            WWS.AUSTRALIA AS AUSTRALIA,
            WWS.Slovenia AS Slovenia,
            WWS.S2 AS S2,
            WWS.S3 AS S3,
            WWS.S4 AS S4,
            WWS.S5 AS S5,
            WWS.S6 AS S6,
            WWS.S7 AS S7,
            WWS.S8 AS S8,
            BI2.LP AS LP,
            WWS.MGSBREED AS MGSBREED,
            WWS.MGSCOUNTRY AS MGSCOUNTRY,
            WWS.MGSIDNO AS MGSIDNO,
            MD.IND AS IND,
            WWS.BIRTH_STATE AS BIRTH_STATE,
            MD.G_IND AS G_IND,
            WWS.HOUSED AS HOUSED,
            MD.HCR AS HCR,
            MD.REL_HCR AS REL_HCR,
            MD.HCR_DTRS AS HCR_DTRS,
            MD.CCR AS CCR,
            MD.REL_CCR AS REL_CCR,
            MD.CCR_DTRS AS CCR_DTRS,
            BI2.STYPE AS STYPE,
            MD.PKEY AS PKEY,
            MD.TKEY AS TKEY,
            MD.ACE_SERV AS ACE_SERV,
            MD.ACE AS ACE,
            MD.ACE_STAR AS ACE_STAR,
            MD.CFI_SERV AS CFI_SERV,
            MD.CFI AS CFI,
            MD.ATA_SERV AS ATA_SERV,
            MD.ATA_SSFS AS ATA_SSFS,
            MD.ATA_STAR AS ATA_STAR,
            MD.STATUS AS STATUS,
            WWS.UDT AS UDT,
            HPD.HH0 AS HH0,
            HPD.HH1 AS HH1,
            HPD.HH2 AS HH2,
            HPD.HH3 AS HH3,
            HPD.HH4 AS HH4,
            HPD.HH5 AS HH5,
            HPD.HHB AS HHB,
            HPD.HHC AS HHC,
            HPD.HHD AS HHD,
            HPD.HHM AS HHM,
            HPD.HHP AS HHP,
            HPD.HHR AS HHR,
            HPD.HBR AS HBR,
            HPD.HCD AS HCD,
            MD.CM_DOL,
            MD.FM_DOL,
            MD.GM_DOL,
            MD.FE,
            MD.FI,
            WWS.SEXED_ONLY,
            W.MAST,
            W.MAST_REL,
            W.MAST_DAU,
            W.LAME,
            W.LAME_REL,
            W.LAME_DAU,
            W.MET,
            W.MET_REL,
            W.MET_DAU,
            W.RP,
            W.RP_REL,
            W.RP_DAU,
            W.KET,
            W.KET_REL,
            W.KET_DAU,
            W.DA,
            W.DA_REL,
            W.DA_DAU,
            W.HP,
            W.WT,
            W.DWP,
            MD.LIV,
            MD.REL_LIV,
            MD.SGL,
            MD.SGL_REL,
            MD.SGL_DTRS,
            MD.SGL_HRDS,
		  SCRH.SCR AS RAW_SCR,
		  SCRH.SERV_SCR AS RAW_SERV_SCR
     FROM dbo.WWSBULLS AS WWS
          LEFT JOIN dbo.BULLINDEX AS BI
		  ON WWS.UID = BI.UID
          INNER JOIN dbo.BI_CODENO AS BI2
		  ON BI.CODENO = BI2.CODENO
          LEFT JOIN dbo.Megadairy AS MD 
		  ON WWS.UID = MD.UID
          LEFT JOIN dbo.HaplotypeData AS HPD 
		  ON WWS.UID = HPD.UID
          LEFT JOIN dbo.ecstatus AS ec 
		  ON BI2.EC = ec.EC
          LEFT JOIN dbo.WELLNESS W 
		  ON W.UID = WWS.UID
	     LEFT JOIN dbo.scr_history AS SCRH
		  ON SCRH.UID = WWS.UID
     WHERE WWS.BREED = 'HO'
           OR WWS.BREED = 'WW';
GO