SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[ADM_Pending_Orders] as
SELECT 'PO' AS Source, POGB.cntry_name, POGB.cust_name, POGB.ITEM_KEY, ho.CODENAME, POGB.doses,POGB.wws_cost, 
POGB.agent_cost,  POGB.cust_net,  CAST(POGB.pending_GP AS DECIMAL(4,1)) AS OM2_GP, ho.YS, 
CASE WHEN POGB.cntry_name='Australia' THEN ho.Australia WHEN POGB.cntry_name="Russia" THEN ho.Russia ELSE '' END AS MKTG, 
ho.NEW, ho.CODENO, ho.REGNAME, AP.NEWCOST, AP.NEWSELL, CAST((AP.NEWSELL-AP.NEWCOST)/AP.NEWSELL*100 AS DECIMAL (4,1)) AS GP, 
AP.COMMENT, AP.COST500, AP.SELL500, ho.EC, ho.IBR, ho.LEU, ho.BT, ho.UDT, ho.DOB, ho.HOUSED, ho.D, POGB.rep_key, POGB.cust_key
FROM ((dbo.HOLSTEINQUERY AS ho INNER JOIN dbo.BULLINDEX AS BI ON ho.UID = BI.UID) 
INNER JOIN VS1DB2.OM2.dbo.LHA_PendingOrdersGroupBy AS POGB ON BI.ITEM_KEY = POGB.item_key) 
INNER JOIN dbo.ALL_PRICES_QRY AS AP ON (ho.CODENO = AP.CODENO) AND (BI.CODENO = AP.CODENO)
UNION ALL SELECT 'PO' AS Source, POGB.cntry_name, POGB.cust_name, POGB.ITEM_KEY, ho.CODENAME, POGB.doses, POGB.wws_cost, 
POGB.agent_cost,  POGB.cust_net,  CAST(POGB.pending_GP AS DECIMAL(4,1)) AS OM2_GP, ho.YS, 
CASE WHEN POGB.cntry_name='Australia' THEN ho.Australia WHEN POGB.cntry_name="Russia" THEN ho.Russia ELSE '' END AS MKTG, 
ho.NEW, ho.CODENO, ho.REGNAME, AP.NEWCOST, AP.NEWSELL, CAST((AP.NEWSELL-AP.NEWCOST)/AP.NEWSELL*100 AS DECIMAL (4,1)) AS GP, 
AP.COMMENT, AP.COST500, AP.SELL500, ho.EC, ho.IBR, ho.LEU, ho.BT, ho.UDT, ho.DOB, ho.HOUSED, ho.D, POGB.rep_key, POGB.cust_key
FROM ((dbo.COLORQUERY AS ho INNER JOIN dbo.BULLINDEX AS BI ON ho.UID = BI.UID) 
INNER JOIN VS1DB2.OM2.dbo.LHA_PendingOrdersGroupBy AS POGB ON BI.ITEM_KEY = POGB.item_key) 
INNER JOIN dbo.ALL_PRICES_QRY AS AP ON (ho.CODENO = AP.CODENO) AND (BI.CODENO = AP.CODENO)

GO