SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[MARSXDBULLS_VIEW]  WITH SCHEMABINDING AS


select MI.ACTIVE, MI.DEL, MAR.YS, MAR.NEW, MAR.REGNAME, MAR.CODENAME, MI.CODENO ,MSXDP.OLDCOST, MSXDP.NEWCOST, MSXDP.DECREASE, MSXDP.OLDSELL, 
MSXDP.NEWSELL, MSXDP.OLDRETAIL, MSXDP.RETAIL, MSXDP.COMMENT, MSXDP.INVENTORY, MSXDP.EU_INVENTORY, MAR.HOUSED, MAR.IDNO, MAR.STUD, MAR.UID, MSXDP.STYPE, MAR.BREED 
FROM dbo.MARBULLS MAR INNER JOIN dbo.MARINDEX MI on MI.UID = MAR.UID AND MI.STYPE = 'X' and MI.ACTIVE = -1
LEFT OUTER JOIN dbo.MARSXDPRICE MSXDP ON MSXDP.CODENO = MI.CODENO

GO