SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE VIEW [dbo].[WWSBULLS_LP] WITH SCHEMABINDING AS
SELECT BI.ACTIVE, BI.LP, BI.STYPE, BI.DEL, WWS.NEW, WWS.YS, WWS.REGNAME, WWS.RECESS, WWS.RECESS_PREV, WWS.D, WWS.CODENAME, BI.CODENO, 
WWS.BREED, WWS.STUD, WWS.LOCATION, WWS.COUNTRY, WWS.IDNO, WWS.DOB, WWS.KC, WWS.BLG, WWS.BCN, WWS.IBR, WWS.LEU, WWS.BT, BI.EC, EC.ECSTATUS, 
EC.QUALIFIED, BI.QUAL, BI.CONC, WWS.PEDIGREE, WWS.SREGNAME, WWS.BLACK_PCT, WWS.AAA, WWS.DMS, WWS.Slovenia, WWS.S2, WWS.S3, WWS.S4, WWS.S5, WWS.S6,
 WWS.S7, WWS.S8, WWS.MGSBREED, WWS.MGSCOUNTRY, WWS.MGSIDNO, WWS.IND, WWS.SBREED, WWS.SCOUNTRY, WWS.SIDNO, WWS.BREEDSORT, WWS.HBSTATUS, 
 WWS.RHAIND, WWS.OIDNO, WWS.BIRTH_STATE, WWS.HOUSED, WWS.CLASS, WWS.UID, WWS.NAABCODE, WWS.SEXED_ONLY, APQ.NEWCOST, APQ.NEWSELL, APQ.RETAIL, 
 APQ.OLDCOST, APQ.OLDSELL, BI.HCOMMENT, BI.ITEM_KEY
FROM ((dbo.ecstatus AS EC RIGHT JOIN (dbo.WWSBULLS AS WWS LEFT JOIN dbo.BULLINDEX AS BI ON WWS.UID = BI.UID) ON EC.EC = BI.EC) 
LEFT JOIN dbo.ALL_PRICES_QRY AS APQ ON BI.CODENO = APQ.CODENO) INNER JOIN dbo.Megadairy AS M ON WWS.UID = M.UID
WHERE (((BI.LP)<>0));
GO