SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[TOP_PROVEN_HO_BASE_VIEW] AS

SELECT M.UID, WWS.IND, WWS.NEW, WWS.REGNAME, WWS.RECESS,H.HCD, case when WWS.SEXED_ONLY <> 0 then BI.CODENO else WWS.CODENO end AS CODENO, 
WWS.SEXED_ONLY, M.NDTRS, M.NHRDS, M.PTAM, M.PTAF_P, M.PTAF, M.REL_MF, M.PTAP_P, M.PTAP, M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, 
M.SCS, M.REL_SCS, M.FI, M.DPR, M.REL_DPR, M.SCE, M.SCE_REL, WT.WT, WT.DWP, M.SCR,M.REL_SCR,M.SERV_SCR,
CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE ELSE M.PEDIGREE END AS MKTG_PEDIGREE, BI.ACTIVE, BI.stype, WWS.STUD AS STUD, M.LIV, M.REL_LIV, M.SGL, M.SGL_REL, M.PKEY, M.TKEY,
WWS.CODENAME
FROM ((dbo.Megadairy AS M INNER JOIN dbo.WWSBULLS AS WWS ON M.UID = WWS.UID) INNER JOIN dbo.BULLINDEX AS BI ON WWS.UID = BI.UID) 
LEFT JOIN dbo.WELLNESS WT ON WT.UID = M.UID
LEFT JOIN dbo.HaplotypeData H on M.UID = H.UID
WHERE (((WWS.SEXED_ONLY)=0) AND ((BI.ACTIVE)<>0) AND ((BI.stype)='C') AND ((WWS.YS) Is Null Or (WWS.YS)='') AND ((WWS.BREED)='HO')) OR (((WWS.SEXED_ONLY)<>0) AND ((BI.ACTIVE)<>0) 
AND ((BI.stype)='X') AND ((WWS.YS) Is Null Or (WWS.YS)='') AND ((WWS.BREED)='HO')) 

UNION ALL SELECT M.UID, '' AS IND, XF.NEW, XF.REGNAME, XF.RECESS,H.HCD, XF.CODENO AS CODENO,0 AS SEXED_ONLY, M.NDTRS, M.NHRDS, M.PTAM, M.PTAF_P, 
M.PTAF, M.REL_MF, M.PTAP_P, M.PTAP, M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, M.SCS, M.REL_SCS, M.FI, M.DPR, 
M.REL_DPR, M.SCE, M.SCE_REL, WT.WT, WT.DWP, M.SCR, M.REL_SCR,M.SERV_SCR,
CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE WHEN M.PEDIGREE IS NOT NULL THEN M.PEDIGREE ELSE XF.PEDIGREE END AS MKTG_PEDIGREE, XF.ACTIVE, 'C' AS STYPE, 
244 AS STUD, M.LIV, M.REL_LIV,M.SGL, M.SGL_REL, M.PKEY, M.TKEY, XF.CODENAME
FROM (dbo.Megadairy AS M INNER JOIN dbo.XFBULLS AS XF ON M.UID = XF.UID)
LEFT JOIN dbo.HaplotypeData H on M.UID = H.UID
LEFT JOIN dbo.WELLNESS WT ON WT.UID = M.UID
WHERE XF.ACTIVE<>0 AND  (XF.YS Is Null Or XF.YS='')  AND XF.BREED = 'HO'

UNION ALL SELECT M.UID, '' AS IND, ABK.NEW, ABK.REGNAME, ABK.RECESS, H.HCD, ABK.CODENO AS CODENO,0 AS SEXED_ONLY, M.NDTRS, M.NHRDS, M.PTAM, M.PTAF_P, M.PTAF,
 M.REL_MF, M.PTAP_P, M.PTAP,M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, M.SCS, M.REL_SCS, M.FI, M.DPR, 
M.REL_DPR, M.SCE, M.SCE_REL, WT.WT, WT.DWP, M.SCR, M.REL_SCR, M.SERV_SCR, 
CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE WHEN M.PEDIGREE IS NOT NULL THEN M.PEDIGREE ELSE ABK.PEDIGREE END AS MKTG_PEDIGREE, ABK.ACTIVE, 'C' AS STYPE, 
235 AS STUD, M.LIV, M.REL_LIV, M.SGL, M.SGL_REL, M.PKEY, M.TKEY, ABK.CODENAME
FROM (dbo.Megadairy AS M INNER JOIN dbo.ABKBULLS AS ABK ON M.UID = ABK.UID)
LEFT JOIN dbo.WELLNESS WT ON WT.UID = M.UID
LEFT JOIN dbo.HaplotypeData H on M.UID = H.UID
WHERE ABK.ACTIVE<>0 AND ABK.BREED = 'HO'

UNION ALL SELECT DISTINCT M.UID, '' AS IND, MAR.NEW, MAR.REGNAME, MAR.RECESS, H.HCD, MAR.CODENO AS CODENO,0 AS SEXED_ONLY, M.NDTRS, M.NHRDS, M.PTAM, M.PTAF_P, M.PTAF, M.REL_MF, M.PTAP_P, M.PTAP, 
M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, M.SCS, M.REL_SCS, M.FI, M.DPR, M.REL_DPR,
M.SCE, M.SCE_REL,  W.WT, W.DWP, M.SCR, M.REL_SCR, M.SERV_SCR, 
CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE WHEN M.PEDIGREE IS NOT NULL THEN M.PEDIGREE ELSE MAR.PEDIGREE END AS MKTG_PEDIGREE, MIX.ACTIVE, 'C' AS STYPE, 
202 AS STUD, M.LIV, M.REL_LIV, M.SGL, M.SGL_REL, M.PKEY, M.TKEY, MAR.CODENAME
FROM (dbo.Megadairy AS M INNER JOIN dbo.MARBULLS AS MAR ON M.UID = MAR.UID) JOIN MARINDEX MIX ON MAR.UID = MIX.UID
LEFT JOIN dbo.WELLNESS W ON W.UID = M.UID
LEFT JOIN dbo.HaplotypeData H on M.UID = H.UID
WHERE MIX.ACTIVE <> 0 AND (MAR.YS Is Null Or MAR.YS='') AND MAR.BREED = 'HO'
GO