SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[BULLINDEX_Missing_Codenos] AS
select M.UID AS UID, M.codeno AS CODENO, 0 AS ACTIVE, 0 AS LP, 
CASE WHEN LEFT(M.CODENO,2) = '00' THEN RIGHT(M.CODENO,8) WHEN LEFT(M.CODENO,1) = '0' THEN RIGHT(M.CODENO,9) ELSE M.CODENO END  AS ITEM_KEY  
from Megadairy M LEFT OUTER join BULLINDEX BI ON M.CODENO = BI.CODENO
WHERE BI.CODENO IS NULL AND M.CODENO IS NOT NULL and ltrim(rtrim(M.CODENO)) <> '' and len(M.CODENO) = 10
UNION ALL select M.UID AS UID, M.NAABCODE2 AS CODENO, 0 AS ACTIVE, 0 AS LP, 
CASE WHEN LEFT(M.NAABCODE2,2) = '00' THEN RIGHT(M.NAABCODE2,8) WHEN LEFT(M.NAABCODE2,1) = '0' THEN RIGHT(M.NAABCODE2,9) ELSE M.NAABCODE2 END  AS ITEM_KEY  
from Megadairy M LEFT OUTER join BULLINDEX BI ON M.NAABCODE2 = BI.CODENO 
WHERE BI.CODENO IS NULL AND M.NAABCODE2 IS NOT NULL and ltrim(rtrim(M.NAABCODE2)) <> '' and len(M.NAABCODE2) = 10
UNION ALL select M.UID AS UID, M.NAABCODE3 AS CODENO, 0 AS ACTIVE, 0 AS LP, 
CASE WHEN LEFT(M.NAABCODE3,2) = '00' THEN RIGHT(M.NAABCODE3,8) WHEN LEFT(M.NAABCODE3,1) = '0' THEN RIGHT(M.NAABCODE3,9) ELSE M.NAABCODE3 END  AS ITEM_KEY  
from Megadairy M LEFT OUTER join BULLINDEX BI ON M.NAABCODE3 = BI.CODENO 
WHERE BI.CODENO IS NULL AND M.NAABCODE3 IS NOT NULL and ltrim(rtrim(M.NAABCODE3)) <> '' and len(M.NAABCODE3) = 10
UNION ALL select M.UID AS UID, M.NAABCODE4 AS CODENO, 0 AS ACTIVE, 0 AS LP, 
CASE WHEN LEFT(M.NAABCODE4,2) = '00' THEN RIGHT(M.NAABCODE4,8) WHEN LEFT(M.NAABCODE4,1) = '0' THEN RIGHT(M.NAABCODE4,9) ELSE M.NAABCODE4 END  AS ITEM_KEY  
from Megadairy M LEFT OUTER join BULLINDEX BI ON M.NAABCODE4 = BI.CODENO 
WHERE BI.CODENO IS NULL AND M.NAABCODE4 IS NOT NULL and ltrim(rtrim(M.NAABCODE4)) <> '' and len(M.NAABCODE4) = 10
UNION ALL select M.UID AS UID, M.NAABCODE5 AS CODENO, 0 AS ACTIVE, 0 AS LP, 
CASE WHEN LEFT(M.NAABCODE5,2) = '00' THEN RIGHT(M.NAABCODE5,8) WHEN LEFT(M.NAABCODE5,1) = '0' THEN RIGHT(M.NAABCODE5,9) ELSE M.NAABCODE5 END  AS ITEM_KEY  
from Megadairy M LEFT OUTER join BULLINDEX BI ON M.NAABCODE5 = BI.CODENO 
WHERE BI.CODENO IS NULL AND M.NAABCODE5 IS NOT NULL and ltrim(rtrim(M.NAABCODE5)) <> '' and len(M.NAABCODE5) = 10
UNION ALL select M.UID AS UID, M.NAABCODE6 AS CODENO, 0 AS ACTIVE, 0 AS LP, 
CASE WHEN LEFT(M.NAABCODE6,2) = '00' THEN RIGHT(M.NAABCODE6,8)  WHEN LEFT(M.NAABCODE6,1) = '0' THEN RIGHT(M.NAABCODE6,9) ELSE M.NAABCODE6 END  AS ITEM_KEY  
from Megadairy M LEFT OUTER join BULLINDEX BI ON M.NAABCODE6 = BI.CODENO 
WHERE BI.CODENO IS NULL AND M.NAABCODE6 IS NOT NULL and ltrim(rtrim(M.NAABCODE6)) <> '' and len(M.NAABCODE6) = 10
GO