SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CPRICE_VIEW] WITH SCHEMABINDING AS
SELECT BI.ACTIVE, BI.DEL, WWS.NEW, WWS.YS, BI.LP, BI.EC, BI.STYPE,
CP.INACTIVE, CP.CODENO, CP.CODENAME, CP.REGNAME, CP.OLDCOST, CP.NEWCOST,
CP.DECREASE, CP.OLDSELL, CP.NEWSELL, CP.OLDRETAIL, CP.RETAIL, 
CP.COST500, CP.SELL500, R.Royalty, CP.COMMENT,BI.HCOMMENT, BLM.Current_Inv AS INVENTORY,
BLM.Current_EU_Inv AS EU_INVENTORY, WWS.COUNTRY, WWS.IDNO, WWS.STUD, WWS.HOUSED,
WWS.UID, WWS.IBR, WWS.leu, WWS.bt, WWS.d, WWS.BREED, WWS.UDT,WWS.DOB, BI.ITEM_KEY
FROM ([dbo].[WWSBULLS] AS WWS INNER JOIN [dbo].[CPRICE] as CP ON WWS.CODENO = CP.CODENO) 
INNER JOIN [dbo].[BULLINDEX] as BI ON CP.CODENO = BI.CODENO
LEFT OUTER JOIN [dbo].[BullsLocationMaster] BLM on BLM.MKTG_CODENO = CP.CODENO
LEFT OUTER JOIN [dbo].[Royalties] R on R.UID = WWS.UID
GO