SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ALL_ACTIVE_SS_AG_ABK_XF_250_714] AS

SELECT M.UID, WWS.IND, WWS.NEW, WWS.REGNAME, WWS.RECESS, CASE WHEN dbo.HaplotypeData.HCD IS NULL THEN '' ELSE dbo.HaplotypeData.HCD END AS HCD, case when WWS.SEXED_ONLY = 0 then [WWS].[CODENO] else [BI].[CODENO] end AS CODENO, WWS.SEXED_ONLY, M.PTAM, M.PTAF_P, 
M.PTAF, M.REL_MF, M.PTAP_P, M.PTAP, M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, M.SCS, M.REL_SCS, M.FI, M.DPR, M.REL_DPR, M.SCE, M.SCE_REL, M.SCR, M.REL_SCR,
/*case when M.serv_scr = 0 then 'N/A' when M.serv_scr Is Null then 'N/A' else Format(M.scr,'0.0') end AS SCR,
case when M.SERV_SCR = 0 then 'N/A' when M.SERV_SCR Is Null  then 'N/A' else M.REL_SCR END  as REL_SCR, */
M.SERV_SCR, CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE ELSE M.PEDIGREE END AS MKTG_PEDIGREE, WWS.YS, BI.stype, M.STUD
FROM ((dbo.Megadairy AS M INNER JOIN dbo.WWSBULLS AS WWS ON M.UID = WWS.UID) INNER JOIN dbo.BULLINDEX AS BI ON WWS.UID = BI.UID) LEFT JOIN dbo.HaplotypeData ON M.UID = dbo.HaplotypeData.UID
WHERE (WWS.SEXED_ONLY=0  AND BI.stype='C' AND BI.ACTIVE<>0 AND WWS.BREED='HO')  OR
 (WWS.SEXED_ONLY<>0  AND BI.stype='X' AND BI.ACTIVE<>0 AND WWS.BREED='HO')

UNION ALL SELECT M.UID, '' AS IND, XF.NEW, XF.REGNAME, XF.RECESS, CASE WHEN dbo.HaplotypeData.HCD IS NULL THEN '' ELSE dbo.HaplotypeData.HCD END AS HCD, XF.CODENO AS CODENO, 0 AS SEXED_ONLY, M.PTAM, M.PTAF_P, 
M.PTAF, M.REL_MF, M.PTAP_P, M.PTAP, M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, M.SCS, M.REL_SCS, M.FI, M.DPR, M.REL_DPR, M.SCE, M.SCE_REL, M.SCR, M.REL_SCR,
/*case when M.serv_scr = 0 then 'N/A' when M.serv_scr Is Null then 'N/A' else Format(M.scr,'0.0') end AS SCR,
case when M.SERV_SCR = 0 then 'N/A' when M.SERV_SCR Is Null  then 'N/A' else M.REL_SCR END  as REL_SCR, */
M.SERV_SCR, CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE WHEN M.PEDIGREE IS NOT NULL THEN M.PEDIGREE ELSE XF.PEDIGREE END AS MKTG_PEDIGREE, XF.YS, 'C' AS STYPE, 244 AS STUD
FROM dbo.Megadairy AS M INNER JOIN dbo.XFBULLS AS XF ON M.UID = XF.UID LEFT JOIN dbo.HaplotypeData ON M.UID = dbo.HaplotypeData.UID
WHERE XF.ACTIVE <> 0 AND XF.BREED = 'HO'

/*  No YS column curently in table - comment out for now until we have column and have some Genomic bulls */
 UNION ALL SELECT M.UID, '' AS IND, ABK.NEW, ABK.REGNAME, ABK.RECESS, CASE WHEN dbo.HaplotypeData.HCD IS NULL THEN '' ELSE dbo.HaplotypeData.HCD END AS HCD, ABK.CODENO AS CODENO, 0 AS SEXED_ONLY, M.PTAM, M.PTAF_P, 
M.PTAF, M.REL_MF, M.PTAP_P, M.PTAP, M.REL_YLD, M.PTAT, M.TREL, M.UDC, M.FLC, M.TPI, M.NM, M.PL, M.REL_PL, M.FE, M.SCS, M.REL_SCS, M.FI, M.DPR, M.REL_DPR, M.SCE, M.SCE_REL, M.SCR, M.REL_SCR,
/*case when M.serv_scr = 0 then 'N/A' when M.serv_scr Is Null then 'N/A' else Format(M.scr,'0.0') end AS SCR,
case when M.SERV_SCR = 0 then 'N/A' when M.SERV_SCR Is Null  then 'N/A' else M.REL_SCR END  as REL_SCR, */
M.SERV_SCR, CASE WHEN M.MKTG_PEDIGREE IS NOT NULL THEN M.MKTG_PEDIGREE WHEN M.PEDIGREE IS NOT NULL THEN M.PEDIGREE ELSE ABK.PEDIGREE END AS MKTG_PEDIGREE, '' AS YS, 'C' AS STYPE, 235 AS STUD
FROM dbo.Megadairy AS M INNER JOIN dbo.ABKBULLS AS ABK ON M.UID = ABK.UID LEFT JOIN dbo.HaplotypeData ON M.UID = dbo.HaplotypeData.UID
WHERE ABK.ACTIVE <> 0 AND ABK.BREED = 'HO'

GO