SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MegadairyCodenos] AS
select '1' as NAAB_NO, M.UID, M.CODENO FROM Megadairy M
UNION ALL SELECT '2' as NAAB_NO,M.UID, M.NAABCODE2 FROM Megadairy M where M.NAABCODE2 IS NOT NULL and M.NAABCODE2 <> ''
UNION ALL SELECT '3' as NAAB_NO,M.UID, M.NAABCODE3 FROM Megadairy M where M.NAABCODE3 IS NOT NULL and M.NAABCODE3 <> ''
UNION ALL SELECT '4' as NAAB_NO,M.UID, M.NAABCODE4 FROM Megadairy M where M.NAABCODE4 IS NOT NULL and M.NAABCODE4 <> ''
UNION ALL SELECT '5' as NAAB_NO,M.UID, M.NAABCODE5 FROM Megadairy M where M.NAABCODE5 IS NOT NULL and M.NAABCODE5 <> ''
UNION ALL SELECT '6' as NAAB_NO,M.UID, M.NAABCODE6 FROM Megadairy M where M.NAABCODE6 IS NOT NULL and M.NAABCODE6 <> ''

GO