SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE VIEW [dbo].[GENERVATIONSQUERY] AS
SELECT MD.FI, BI.ACTIVE AS ACTIVE, BI.DEL AS DEL, WWS.NEW AS NEW, WWS.YS AS YS, WWS.UID AS UID,
WWS.REGNAME AS REGNAME, WWS.RECESS AS RECESS, WWS.D AS D, WWS.CODENAME AS CODENAME, BI.CODENO AS
CODENO, WWS.BREED AS BREED, WWS.COUNTRY AS COUNTRY, WWS.IDNO AS IDNO, WWS.STUD AS STUD, WWS.DOB AS
DOB, MD.LOCATION, MD.SOURCE AS SOURCE, MD.NDTRS AS NDTRS, MD.NHRDS AS NHRDS, MD.PTAM AS PTAM,
MD.PTAF_P AS PTAF_P, MD.PTAF AS PTAF, MD.PTAP_P AS PTAP_P, MD.PTAP AS PTAP, MD.REL_YLD AS REL_YLD,
MD.REL_MF AS REL_MF, MD.PREL AS PREL, MD.NM AS NM, MD.REL_NM AS REL_NM, MD.PL AS PL, MD.REL_PL AS
REL_PL, MD.SCS AS SCS, MD.REL_SCS AS REL_SCS, MD.DPR AS DPR, MD.REL_DPR AS REL_DPR, MD.MILK AS MILK,
MD.FAT_P AS FAT_P, MD.FAT AS FAT, MD.PROTM AS PROTM, MD.PRO_P AS PRO_P, MD.PRO AS PRO, MD.NM_PCTILE
AS NM_PCTILE, MD.TPI AS TPI, MD.TSOURCE AS TSOURCE, MD.TDATE AS TDATE, MD.TDTRS AS TDTRS, MD.THRDS
AS THRDS, MD.PTAT AS PTAT, MD.TREL AS TREL, MD.UDC AS UDC, MD.FLC AS FLC, MD.BDC AS BDC, MD.DC AS
DC, MD.LDTRS AS LDTRS, MD.LHRDS AS LHRDS, MD.STAT AS STAT, MD.Str AS STR, MD.BD AS BD, MD.DF AS DF,
MD.RA AS RA, MD.THURLW AS THURLW, MD.RLS AS RLS, MD.RLR AS RLR, MD.FA AS FA, MD.FLS AS FLS, MD.FUA
AS FUA, MD.RUH AS RUH, MD.RUW AS RUW, MD.UC AS UC, MD.UD AS UD, MD.FTP AS FTP, MD.RTP AS RTP,
MD.TEATL AS TEATL, MD.CEDATE AS CEDATE, MD.SCE AS SCE, MD.PRELIM AS PRELIM, MD.SCE_OBS AS SCE_OBS,
MD.SCE_REL AS SCE_REL, MD.DCE AS DCE, MD.DCE_OBS AS DCE_OBS, MD.DCE_REL AS DCE_REL, MD.SSB_PCT AS
SSB_PCT, MD.SSB_OBS AS SSB_OBS, MD.SSB_REL AS SSB_REL, MD.SSB_SOURCE AS SSB_SOURCE, MD.SSB_OFF AS
SSB_OFF, MD.DSB_PCT AS DSB_PCT, MD.DSB_OBS AS DSB_OBS, MD.DSB_REL AS DSB_REL, MD.MS AS MS, MD.DIS AS
DIS, case when MD.SERV_SCR Is Null then NULL ELSE Round(MD.SCR,1) END AS SCR, 
case when MD.SERV_SCR Is Null then NULL ELSE MD.SERV_SCR END AS SERV_SCR,
case when MD.SERV_SCR Is Null then NULL ELSE MD.REL_SCR END AS REL_SCR,  MD.EVALDATE AS EVALDATE, MD.SREGNAME AS SREGNAME, MD.SIDNO AS
SIDNO, MD.SBREED AS SBREED, MD.SCOUNTRY AS SCOUNTRY, MD.DREGNAME AS DREGNAME, MD.HBSTATUS AS
HBSTATUS, MD.RHAIND AS RHAIND, WWS.BREEDSORT AS BREEDSORT, BI.QUAL AS QUAL, BI.CONC AS CONC, WWS.KC
AS KC, WWS.BLG AS BLG, WWS.BCN AS BCN, WWS.IBR AS IBR, WWS.LEU AS LEU, WWS.BT AS BT, WWS.EHD AS EHD,
WWS.JOHNES AS JOHNES, BI.EC AS EC, ec.ECSTATUS AS ECSTATUS, ec.QUALIFIED AS QUALIFIED, BI.HCOMMENT
AS HCOMMENT, WWS.PEDIGREE AS PEDIGREE, MD.BLACK_PCT, WWS.AAA AS AAA, MD.DMS, MD.SAUDI, MD.UKLIST,
MD.IRAN, MD.Russia, MD.RSA, MD.ITALYLIST, MD.AUSTRALIA, MD.S1, MD.S2, MD.S3, MD.S4, MD.S5, MD.S6,
MD.S7, MD.S8, BI.LP AS LP, MD.MGSBREED, MD.MGSCOUNTRY, WWS.MGSIDNO AS MGSIDNO, MD.IND AS IND,
WWS.BIRTH_STATE AS BIRTH_STATE, MD.G_IND AS G_IND, WWS.HOUSED AS HOUSED, MD.HCR AS HCR, MD.REL_HCR
AS REL_HCR, MD.HCR_DTRS AS HCR_DTRS, MD.CCR AS CCR, MD.REL_CCR AS REL_CCR, MD.CCR_DTRS AS CCR_DTRS,
BI.STYPE AS STYPE, MD.PKEY AS PKEY, MD.TKEY AS TKEY, MD.ACE_SERV AS ACE_SERV, MD.ACE AS ACE,
MD.ACE_STAR AS ACE_STAR, MD.CFI_SERV AS CFI_SERV, MD.CFI AS CFI, MD.ATA_SERV AS ATA_SERV,
MD.ATA_SSFS AS ATA_SSFS, MD.ATA_STAR AS ATA_STAR, MD.STATUS AS STATUS, WWS.UDT AS UDT, HPD.HH0 AS
HH0, HPD.HH1 AS HH1, HPD.HH2 AS HH2, HPD.HH3 AS HH3, HPD.HH4 AS HH4, HPD.HH5 AS HH5, HPD.HHB AS HHB,
HPD.HHC AS HHC, HPD.HHD AS HHD, HPD.HHM AS HHM, HPD.HHP AS HHP, HPD.HHR AS HHR, MD.CM_DOL FROM
(((dbo.WWSBULLS AS WWS LEFT JOIN dbo.BULLINDEX AS BI ON WWS.UID = BI.UID) LEFT JOIN dbo.Megadairy AS
MD ON WWS.UID = MD.UID) LEFT JOIN dbo.HaplotypeData AS HPD ON WWS.UID = HPD.UID) LEFT JOIN
dbo.ecstatus AS ec ON BI.EC = ec.EC WHERE (((WWS.BREED)='HO' Or (WWS.BREED)='WW')) AND WWS.STUD =
250;

GO