SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE VIEW [dbo].[BI_CODENO] WITH SCHEMABINDING AS
SELECT dbo.BULLINDEX.CODENO, dbo.BULLINDEX.ACTIVE, dbo.BULLINDEX.DEL, dbo.BULLINDEX.LP, dbo.BULLINDEX.EC, 
dbo.BULLINDEX.HCOMMENT, dbo.BULLINDEX.AVAILABILITY, dbo.BULLINDEX.QUAL, dbo.BULLINDEX.CONC, dbo.BULLINDEX.STYPE, 
dbo.BULLINDEX.ITEM_KEY FROM dbo.BULLINDEX;
GO