SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[bullscon_unique]
AS
  SELECT b.UID,
         b.BREED,
         b.COUNTRY,
         b.IDNO,
         b.HBSTATUS,
         b.RHAIND,
         b.REGNAME,
         b.RECESS,
         b.SBREED,
         b.SCOUNTRY,
         b.SIDNO,
         b.SHBSTATUS,
         b.SRHAIND,
         b.SREGNAME,
         b.SRECESS,
         b.DBREED,
         b.DCOUNTRY,
         b. DIDNO,
         b.DHBSTATUS,
         b.DRHAIND,
         b.DREGNAME,
         b.DRECESS,
         b.DOB,
         b.CODENO,
         b.STATUS,
         b.DATEPTAT,
         b.STAPTAT,
         b.PTAT,
         b.TREL,
         b.TRECORDS,
         b.TDTRS,
         b.TGRDDTRS,
         b.THRDS,
         b.THRD_CLASS,
         b.EFF_DTRS,
         b. AFSCDTRS,
         b.AASCDTRS,
         b.SDAASC,
         b.NSTATES,
         b.NYRS,
         b.INDICATOR,
         b.DATELIN,
         b.LREL,
         b.LRECORDS,
         b.LDTRS,
         b.LHRDS,
         b.LHRD_CLASS,
         b.LEFFDTRS,
         b.STAT,
         b.DA_STAT,
         b.SD_STAT,
         b.STR,
         b.DA_STR,
         b.SD_STR,
         b. BD,
         b.DA_BD,
         b.SD_BD,
         b.DF,
         b.DA_DF,
         b.SD_DF,
         b.RA,
         b.DA_RA,
         b.SD_RA,
         b.THURLW,
         b.DA_THURLW,
         b.SD_THURLW,
         b.RLS,
         b.DA_RLS,
         b.SD_RLS,
         b.RLR,
         b.DA_RLR,
         b.SD_RLR,
         b.FA,
         b.DA_FA,
         b.SD_FA,
         b.FLS,
         b.DA_FLS,
         b.SD_FLS,
         b. FUA,
         b.DA_FUA,
         b.SD_FUA,
         b.RUH,
         b.DA_RUH,
         b.SD_RUH,
         b.RUW,
         b.DA_RUW,
         b.SD_RUW,
         b.UC,
         b.DA_UC,
         b.SD_UC,
         b.UD,
         b.DA_UD,
         b.SD_UD,
         b.FTP,
         b.DA_FTP,
         b.SD_FTP,
         b.RTP,
         b.DA_RTP,
         b.SD_RTP,
         b.TEATL,
         b.DA_TEATL,
         b. SD_TEATL,
         b.UDC,
         b.FLC,
         b.BDC,
         b.DC,
         b.TKEY,
         b.TDATE,
         b.TSOURCE
  FROM   [Dairy].[dbo].[bullscon] b
         LEFT OUTER JOIN [Dairy].[dbo].[HTYPE] H
                      ON b.UID = H.[UID]
  WHERE  H.[UID] IS NULL
GO