SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[ID38_PEDIGREES] AS
SELECT id.UID AS UID, ID.CODENO AS CODENO,
ltrim(rtrim(ID.CODENAME)) AS CODENAME, 
ltrim(rtrim(ID.REGNAME)) AS REGNAME, 
ID1.CODENO AS SIRE_CODENO, 
ltrim(rtrim(ID1.CODENAME)) AS SIRE_CODENAME, 
ltrim(rtrim(ID1.REGNAME)) AS SIRE_REGNAME, 
ID2.CODENO AS MGS_CODENO, 
ltrim(rtrim(ID2.CODENAME)) AS MGS_CODENAME, 
ltrim(rtrim(ID2.REGNAME)) AS MSG_REGNAME, 
ID3.CODENO AS MGGDS_CODENO, 
ltrim(rtrim(ID3.CODENAME)) AS MGGDS_CODENAME, 
ltrim(rtrim(ID3.REGNAME)) AS MGGDS_REGNAME, 
concat(CASE WHEN ltrim(rtrim(ID1.CODENAME)) IS NOT NULL THEN ltrim(rtrim(ID1.CODENAME)) ELSE concat([ID].[SBREED],[ID].[SCOUNTRY],[ID].[SIDNO]) END,' X ', 
CASE WHEN ltrim(rtrim(ID2.CODENAME)) IS NOT NULL THEN ltrim(rtrim(ID2.CODENAME)) ELSE concat([ID].[MGSBREED],[ID].[MGSCOUNTRY],[ID].[MGSIDNO]) END,' X ',
CASE WHEN ltrim(rtrim(ID3.CODENAME)) IS NOT NULL THEN ltrim(rtrim(ID3.CODENAME))  ELSE concat([ID].[MGDSBREED],[ID].[MGDSCOUNTRY],[ID].[MGDSIDNO]) END) AS PEDIGREE,
concat(CASE WHEN ltrim(rtrim(ID1.CODENAME)) IS NOT NULL THEN 
CASE WHEN LEFT(ltrim(rtrim(ID1.CODENAME)),4) = 'ALTA' THEN RIGHT(ltrim(rtrim(ID1.CODENAME)),LEN(ID1.CODENAME)-4) ELSE ltrim(rtrim(ID1.CODENAME)) END
ELSE concat([ID].[SBREED],[ID].[SCOUNTRY],[ID].[SIDNO]) END,' X ', 
CASE WHEN ltrim(rtrim(ID2.CODENAME)) IS NOT NULL THEN 
CASE WHEN LEFT(ltrim(rtrim(ID2.CODENAME)),4) = 'ALTA' THEN RIGHT(ltrim(rtrim(ID2.CODENAME)),LEN(ID2.CODENAME)-4) ELSE ltrim(rtrim(ID2.CODENAME)) END 
ELSE concat([ID].[MGSBREED],[ID].[MGSCOUNTRY],[ID].[MGSIDNO]) END,' X ',
CASE WHEN ltrim(rtrim(ID3.CODENAME)) IS NOT NULL THEN 
CASE WHEN LEFT(ltrim(rtrim(ID3.CODENAME)),4) = 'ALTA' THEN RIGHT(ltrim(rtrim(ID3.CODENAME)),LEN(ID3.CODENAME)-4) ELSE ltrim(rtrim(ID3.CODENAME)) END 
ELSE concat([ID].[MGDSBREED],[ID].[MGDSCOUNTRY],[ID].[MGDSIDNO]) END) AS MKTG_PEDIGREE
FROM dbo.[38ID] AS ID 
LEFT OUTER JOIN dbo.[38ID] AS ID1 ON [ID1].[UID] = concat([ID].[SBREED],[ID].[SCOUNTRY],[ID].[SIDNO]) 
LEFT OUTER JOIN dbo.[38ID] AS ID2 ON [ID2].[UID] = concat([ID].[MGSBREED],[ID].[MGSCOUNTRY],[ID].[MGSIDNO]) 
LEFT OUTER JOIN dbo.[38ID] AS ID3 ON [ID3].[UID] = concat([ID].[MGDSBREED],[ID].[MGDSCOUNTRY],[ID].[MGDSIDNO])

GO