SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE VIEW [dbo].[ABK_SPAINPRICE_VIEW] WITH SCHEMABINDING AS
SELECT dbo.ABKBULLS.ACTIVE, dbo.ABKBULLS.DEL, dbo.SPAINPRICE.NEW, dbo.SPAINPRICE.YS, dbo.ABKBULLS.EC, dbo.SPAINPRICE.STYPE, dbo.SPAINPRICE.INACTIVE, 
dbo.SPAINPRICE.CODENO, dbo.SPAINPRICE.CODENAME, 
dbo.SPAINPRICE.REGNAME, dbo.SPAINPRICE.OLDCOST, dbo.SPAINPRICE.NEWCOST, dbo.SPAINPRICE.DECREASE, dbo.SPAINPRICE.OLDSELL, dbo.SPAINPRICE.NEWSELL, 
dbo.SPAINPRICE.OLDRETAIL, dbo.SPAINPRICE.RETAIL, 
dbo.SPAINPRICE.COMMENT,dbo.ABKBULLS.HCOMMENT, dbo.ABKBULLS.COUNTRY, dbo.SPAINPRICE.IDNO, dbo.SPAINPRICE.STUD, dbo.ABKBULLS.IBR, dbo.ABKBULLS.LEU, 
dbo.ABKBULLS.BT, dbo.ABKBULLS.D, dbo.ABKBULLS.BREED, dbo.ABKBULLS.DOB, dbo.SPAINPRICE.INVENTORY, dbo.SPAINPRICE.EU_INVENTORY, dbo.SPAINPRICE.CODENO AS ITEM_KEY
FROM dbo.ABKBULLS INNER JOIN dbo.SPAINPRICE ON dbo.ABKBULLS.CODENO = dbo.SPAINPRICE.CODENO;

GO

SET QUOTED_IDENTIFIER ON
GO

CREATE UNIQUE CLUSTERED INDEX [idx_ABK_SPAINPRICE_VIEW_ITEM_KEY]
  ON [dbo].[ABK_SPAINPRICE_VIEW] ([ITEM_KEY], [CODENO])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [idx_ABK_SPAINPRICE_VIEW_CODENO]
  ON [dbo].[ABK_SPAINPRICE_VIEW] ([CODENO])
  ON [PRIMARY]
GO