SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE 	VIEW [dbo].[MEGAWWSBULLS] as

SELECT BI.ACTIVE, BI.LP, BI.DEL, WWS.NEW, WWS.REGNAME, WWS.RECESS, WWS.CODENAME, WWS.CODENO, WWS.BREED, WWS.COUNTRY, WWS.IDNO, EC.QUALIFIED, WWS.YS,WWS.SEXED_ONLY, WWS.STUD 
FROM dbo.WWSBULLS WWS LEFT JOIN (dbo.ecstatus EC RIGHT JOIN dbo.BULLINDEX BI ON EC.EC = BI.EC) ON WWS.CODENO = BI.CODENO WHERE WWS.SEXED_ONLY = 0 
UNION ALL SELECT BI.ACTIVE, BI.LP, BI.DEL, WWS.NEW, WWS.REGNAME, WWS.RECESS, WWS.CODENAME, BI.CODENO, WWS.BREED, WWS.COUNTRY, WWS.IDNO, EC.QUALIFIED, WWS.YS,WWS.SEXED_ONLY, WWS.STUD 
FROM dbo.WWSBULLS WWS LEFT JOIN (dbo.ecstatus EC RIGHT JOIN dbo.BULLINDEX BI ON EC.EC = BI.EC) ON WWS.UID = BI.UID 
WHERE WWS.SEXED_ONLY <> 0 AND BI.STYPE = 'X' AND  LEFT(BI.CODENO,3) <> '514'
UNION ALL SELECT ABK.ACTIVE,NULL, ABK.DEL, ABK.NEW, ABK.REGNAME, ABK.RECESS, ABK.CODENAME, ABK.CODENO, ABK.BREED,
 ABK.COUNTRY, ABK.IDNO, ABK.QUALIFIED, NULL, 0, 235 FROM ABKBULLS ABK 
UNION ALL SELECT MI.ACTIVE, NULL, MI.DEL, MAR.NEW, MAR.REGNAME, MAR.RECESS, MAR.CODENAME, MAR.CODENO, MAR.BREED,
 MAR.COUNTRY, MAR.IDNO, EC.QUALIFIED, MAR.YS, MAR.SEXED_ONLY, 202 FROM MARBULLS MAR RIGHT JOIN MARINDEX MI ON MI.CODENO = MAR.CODENO LEFT JOIN dbo.ecstatus EC ON EC.EC = MI.EC WHERE MAR.SEXED_ONLY = 0
 UNION ALL SELECT MI.ACTIVE, NULL, MI.DEL, MAR.NEW, MAR.REGNAME, MAR.RECESS, MAR.CODENAME, MI.CODENO, MAR.BREED,
 MAR.COUNTRY, MAR.IDNO, EC.QUALIFIED, MAR.YS, MAR.SEXED_ONLY, 202 FROM MARBULLS MAR RIGHT JOIN MARINDEX MI ON MI.uid = MAR.uid LEFT JOIN dbo.ecstatus EC ON EC.EC = MI.EC WHERE MAR.SEXED_ONLY <> 0 
 AND STYPE  = 'X'
 UNION ALL SELECT XF.ACTIVE,NULL, XF.DEL, XF.NEW, XF.REGNAME, XF.RECESS, XF.CODENAME, XF.CODENO, XF.BREED,
 XF.COUNTRY, XF.IDNO, XF.QUALIFIED, NULL, 0, 244 FROM XFBULLS XF;
GO