SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[Kristy_Internal_HO_Prices_Active_and_LP] as
select WWS.NEW, WWS.YS,case when BI.LP <> 0 THEN 'Y' ELSE '' END AS LP, BI.CODENO,  WWS.REGNAME, WWS.CODENAME, WWS.D,  M.PTAM, HP.NEWCOST, HP.NEWSELL,CAST(((HP.NEWSELL-HP.NEWCOST)/HP.NEWSELL)*100 AS DECIMAL(4,1)) AS GP, HP.RETAIL, 
HP.COMMENT, HP.COST500, HP.SELL500,CAST(((HP.SELL500-HP.COST500)/HP.SELL500)*100 AS DECIMAL(4,1)) AS GRID_GP,  WWS.HOUSED, BI.EC, WWS.DOB, WWS.UDT, HPSXD.NEWCOST AS X_NEWCOST, 
HPSXD.NEWSELL AS X_NEWSELL, CAST(((HPSXD.NEWSELL - HPSXD.NEWCOST)/HPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP, HPSXD.RETAIL AS X_RETAIL, HPSXD.COMMENT AS X_COMMENT, 
BI2.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN Megadairy M on M.UID = WWS.UID JOIN HPRICE HP ON HP.CODENO = BI.CODENO LEFT JOIN BULLINDEX BI2 ON BI.UID = BI2.UID AND 
BI2.STYPE = 'X' and BI2.ACTIVE = -1 AND BI2.CODENO NOT LIKE ('514%') LEFT OUTER JOIN HSXDPRICE HPSXD ON BI2.CODENO = HPSXD.CODENO WHERE BI.STYPE = 'C'  AND (BI.ACTIVE <> 0 or BI.LP <> 0)
UNION ALL select WWS.NEW, WWS.YS,case when BI.LP <> 0 THEN 'Y' ELSE '' END AS LP, BI.CODENO,  WWS.REGNAME, WWS.CODENAME, WWS.D,M.PTAM, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  WWS.HOUSED, NULL, WWS.DOB, WWS.UDT, 
HPSXD.NEWCOST AS X_NEWCOST, HPSXD.NEWSELL AS X_NEWSELL, CAST(((HPSXD.NEWSELL- HPSXD.NEWCOST)/HPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP, HPSXD.RETAIL AS X_RETAIL, 
HPSXD.COMMENT AS X_COMMENT, BI.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN Megadairy M on M.UID = WWS.UID JOIN HSXDPRICE HPSXD ON BI.CODENO = HPSXD.CODENO
WHERE WWS.SEXED_ONLY <> 0 AND (BI.ACTIVE <> 0  OR BI.LP <> 0) AND BI.CODENO NOT LIKE ('514%')
GO