SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[HPRICE_VIEW] WITH SCHEMABINDING AS 
SELECT BI.ACTIVE, BI.DEL, WWS.NEW, WWS.YS, BI.LP, BI.EC, BI.STYPE,
HP.INACTIVE, HP.CODENO, HP.CODENAME, HP.REGNAME, HP.OLDCOST, HP.NEWCOST,
HP.DECREASE, HP.OLDSELL, HP.NEWSELL, HP.OLDRETAIL, HP.RETAIL,
HP.COST500, HP.SELL500, R.Royalty, HP.COMMENT,BI.HCOMMENT, BLM.Current_Inv AS INVENTORY,
BLM.Current_EU_Inv as EU_INVENTORY, WWS.COUNTRY, WWS.IDNO, WWS.STUD, WWS.HOUSED,
WWS.UID, WWS.IBR, WWS.leu, WWS.bt, WWS.d, WWS.BREED, WWS.UDT,WWS.DOB, BI.ITEM_KEY
FROM ([dbo].[WWSBULLS] AS WWS INNER JOIN [dbo].[HPRICE] as HP ON WWS.CODENO = HP.CODENO) 
INNER JOIN [dbo].[BULLINDEX] as BI ON HP.CODENO = BI.CODENO
LEFT OUTER JOIN [dbo].[BullsLocationMaster] BLM on BLM.MKTG_CODENO = HP.CODENO
LEFT OUTER JOIN [dbo].[Royalties] R on R.UID = WWS.UID
GO