SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/* 07/27/2015 ADDED HCD for Aug 2015 Proofs  */

CREATE VIEW [dbo].[HaplotypeData_Active_Lineup] as
select BI.UID, BI.ACTIVE, BI.CODENO, WWS.CODENAME, WWS.REGNAME, HD.HH0, HD.HH1, HD.HH2, HD.HH3, HD.HH4, HD.HH5, HD.HHB, HD.HHC, HD.HHD, HD.HHM, HD.HHP, HD.HHR, HD.HDR, HD.HBR, 
HD.HCD, HD.JH1,HD.JH1_PC, HD.JH2, HD.JH2_PC, HD.JHP, HD.JHP_PC, HD.BH1, HD.BH2, HD.BHD, HD.BHM, HD.BHW, HD.BHP, HD.AH1 
FROM BULLINDEX BI INNER JOIN WWSBULLS WWS ON BI.UID = WWS.UID LEFT OUTER JOIN HaplotypeData HD ON WWS.UID = HD.UID
WHERE BI.ACTIVE <> 0
GO