SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[MARSXDPRICE_VIEW] WITH SCHEMABINDING AS
SELECT MI.ACTIVE, MI.DEL, MAR.NEW,MAR.YS, 0 AS LP, MI.EC,  MI.STYPE, MSXDP.INACTIVE, MSXDP.CODENO,  MAR.CODENAME,  MAR.REGNAME, MSXDP.OLDCOST, 
MSXDP.NEWCOST, MSXDP.DECREASE, MSXDP.OLDSELL, MSXDP.NEWSELL, MSXDP.OLDRETAIL, MSXDP.RETAIL, 
NULL AS COST500, NULL AS SELL500, NULL AS Royalty,  MSXDP.COMMENT, MI.HCOMMENT, MSXDP.INVENTORY, MSXDP.EU_INVENTORY, 
NULL  AS COUNTRY, MSXDP.IDNO, MSXDP.STUD,MSXDP.HOUSED, MSXDP.UID, MAR.IBR, MAR.LEU, MAR.BT, MAR.D, MSXDP.BREED, NULL AS UDT,MAR.DOB, MSXDP.CODENO AS ITEM_KEY 
FROM dbo.MARSXDPRICE MSXDP INNER JOIN dbo.MARBULLS MAR ON MSXDP.UID = MAR.UID INNER JOIN dbo.MARINDEX MI ON MI.UID = MAR.UID AND MI.STYPE = 'X'
WHERE MI.ACTIVE <> 0;

GO