SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ALL_MARPRICES_QRY] WITH SCHEMABINDING AS
select 'M' AS SOURCE,
CASE WHEN MI.ACTIVE <> 0 THEN 'Y' ELSE 'N' END AS ACTIVE,
'N' AS LP,
MI.DEL AS DEL,M.CODENO AS CODENO,M.CODENAME AS CODENAME,
M.OLDCOST AS OLDCOST,
M.DECREASE AS DECREASE,M.OLDSELL AS OLDSELL,
M.NEWCOST AS NEWCOST,
M.NEWSELL AS NEWSELL,
M.RETAIL AS RETAIL,
M.COST500 AS COST500,
M.SELL500 AS SELL500,
M.INACTIVE AS INACTIVE,M.INVENTORY AS INVENTORY,M.EU_INVENTORY AS EU_INVENTORY,right(MI.UID,12) AS IDNO,
MI.ITEM_KEY AS ITEM_KEY, MB.D, MI.EC, M.COMMENT, 0 AS SEXED_ONLY,NULL as ROYALTY
FROM dbo.MARPRICE_VIEW as M inner join dbo.MARINDEX as MI on MI.CODENO = M.CODENO
INNER JOIN dbo.MARBULLS MB ON M.UID = MB.UID where (M.NEWCOST > 0) 

UNION all select 'MSXD' AS SOURCE,
CASE WHEN MI.ACTIVE <> 0 THEN 'Y' ELSE 'N' END AS ACTIVE,
'N' AS LP,
MI.DEL AS DEL,MSXD.CODENO AS CODENO,MSXD.CODENAME AS CODENAME,
MSXD.OLDCOST AS OLDCOST,MSXD.DECREASE AS DECREASE,
MSXD.OLDSELL AS OLDSELL,
MSXD.NEWCOST AS NEWCOST,
MSXD.NEWSELL AS NEWSELL,
MSXD.RETAIL AS RETAIL,
NULL AS COST500,
NULL AS SELL500,
MSXD.INACTIVE AS INACTIVE,MSXD.INVENTORY AS INVENTORY,MSXD.EU_INVENTORY AS EU_INVENTORY,
right(MI.UID,12) AS IDNO,MI.ITEM_KEY AS ITEM_KEY, MB.D, MI.EC, MSXD.COMMENT, 0 AS SEXED_ONLY,  NULL as ROYALTY
FROM dbo.MARSXDPRICE_VIEW as MSXD inner join dbo.MARINDEX as MI on MI.CODENO = MSXD.CODENO 
INNER JOIN dbo.MARBULLS MB ON MB.UID = MSXD.UID  where (MSXD.NEWCOST >0) 
GO