SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE VIEW [dbo].[Kristy_Internal_Color_Prices] as
select WWS.BREED, WWS.NEW, WWS.YS, BI.CODENO, WWS.REGNAME, WWS.CODENAME, WWS.D, CP.NEWCOST, CP.NEWSELL, CAST(((CP.NEWSELL - CP.NEWCOST) /  CP.NEWSELL)*100 AS DECIMAL(4,1)) AS GP, 
CP.RETAIL, CP.COMMENT, CP.COST500, CP.SELL500, CAST(((CP.SELL500 - CP.COST500) /  CP.SELL500)*100 AS DECIMAL(4,1)) AS GRID_GP,  WWS.HOUSED, BI.EC, WWS.DOB, WWS.UDT, 
CPSXD.NEWCOST AS X_NEWCOST, CPSXD.NEWSELL AS X_NEWSELL, CAST(((CPSXD.NEWSELL - CPSXD.NEWCOST)/CPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP, CPSXD.RETAIL AS X_RETAIL,
CPSXD.COMMENT AS X_COMMENT, BI2.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN CPRICE CP ON CP.CODENO = BI.CODENO LEFT JOIN BULLINDEX BI2 ON BI.UID = BI2.UID AND 
BI2.STYPE = 'X' AND BI2.ACTIVE = -1 AND BI2.CODENO NOT LIKE '514%' LEFT OUTER JOIN CSXDPRICE CPSXD ON BI2.CODENO = CPSXD.CODENO WHERE BI.STYPE = 'C' and BI.ACTIVE <> 0 
UNION ALL SELECT WWS.BREED, WWS.NEW, WWS.YS, BI.CODENO, WWS.REGNAME, WWS.CODENAME, WWS.D, NULL, NULL, NULL, NULL, NULL, NULL,NULL, NULL, 
 WWS.HOUSED, NULL, WWS.DOB, WWS.UDT, CPSXD.NEWCOST AS X_NEWCOST, CPSXD.NEWSELL AS X_NEWSELL, CAST(((CPSXD.NEWSELL- CPSXD.NEWCOST)/CPSXD.NEWSELL)*100 AS DECIMAL(4,1)) AS X_GP, 
CPSXD.RETAIL AS X_RETAIL, CPSXD.COMMENT AS X_COMMENT, BI.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN CSXDPRICE CPSXD ON BI.CODENO = CPSXD.CODENO
WHERE WWS.SEXED_ONLY <> 0 AND BI.ACTIVE <> 0 AND BI.CODENO NOT LIKE '514%'

GO