SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[MARPRICE_VIEW] WITH SCHEMABINDING AS
SELECT MI.ACTIVE, MI.DEL, MAR.NEW, MAR.YS, 0 AS LP, MI.EC,  MI.STYPE, MARP.INACTIVE, MARP.CODENO,  MAR.CODENAME,  MAR.REGNAME, MARP.OLDCOST, 
MARP.NEWCOST, MARP.DECREASE, MARP.OLDSELL, MARP.NEWSELL, MARP.OLDRETAIL, MARP.RETAIL, MARP.COST500, MARP.SELL500, NULL AS Royalty,  MARP.COMMENT,
MI.HCOMMENT, MARP.INVENTORY, MARP.EU_INVENTORY, 
NULL  AS COUNTRY, MARP.IDNO, MARP.STUD,MARP.HOUSED, MARP.UID, MAR.IBR, MAR.LEU, MAR.BT, MAR.D, MARP.BREED, NULL AS UDT,MAR.DOB, MARP.CODENO AS ITEM_KEY 
FROM dbo.MARPRICE MARP INNER JOIN dbo.MARBULLS MAR ON MARP.UID = MAR.UID INNER JOIN dbo.MARINDEX MI ON MI.UID = MAR.UID AND MI.STYPE = 'C'
WHERE MI.ACTIVE <> 0;

GO