SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CSXDPRICE_VIEW] WITH SCHEMABINDING AS
SELECT BI.ACTIVE, BI.DEL, WWS.NEW, WWS.YS, BI.LP, BI.EC, BI.STYPE,
CSXDP.INACTIVE, CSXDP.CODENO, CSXDP.CODENAME, CSXDP.REGNAME, CSXDP.OLDCOST, CSXDP.NEWCOST,
CSXDP.DECREASE, CSXDP.OLDSELL, CSXDP.NEWSELL, CSXDP.OLDRETAIL, CSXDP.RETAIL, 
CSXDP.COST500, CSXDP.SELL500, R.ROYALTY, CSXDP.COMMENT,BI.HCOMMENT, BLM.Current_Inv AS INVENTORY,
BLM.Current_EU_Inv AS EU_INVENTORY, WWS.COUNTRY, WWS.IDNO, WWS.STUD, WWS.HOUSED,
WWS.UID, WWS.IBR, WWS.LEU, WWS.BT, WWS.D, WWS.BREED, WWS.UDT,WWS.DOB, BI.ITEM_KEY, WWS.SEXED_ONLY
FROM [dbo].WWSBULLS AS WWS INNER JOIN [dbo].[BULLINDEX] as BI ON WWS.UID = BI.UID
INNER JOIN [dbo].[CSXDPRICE] as CSXDP ON BI.CODENO = CSXDP.CODENO
LEFT OUTER JOIN [dbo].BullsLocationMaster BLM on BLM.MKTG_CODENO = CSXDP.CODENO
LEFT OUTER JOIN [dbo].[Royalties] R on R.UID = WWS.UID 
WHERE BI.STYPE = 'X'
GO