SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[XF_SPAINPRICE_VIEW] WITH SCHEMABINDING AS
SELECT dbo.XFBULLS.ACTIVE, dbo.XFBULLS.DEL, dbo.SPAINPRICE.NEW, dbo.SPAINPRICE.YS, dbo.XFBULLS.EC, dbo.SPAINPRICE.STYPE, dbo.SPAINPRICE.INACTIVE, 
dbo.SPAINPRICE.CODENO, dbo.SPAINPRICE.CODENAME, 
dbo.SPAINPRICE.REGNAME, dbo.SPAINPRICE.OLDCOST, dbo.SPAINPRICE.NEWCOST, dbo.SPAINPRICE.DECREASE, dbo.SPAINPRICE.OLDSELL, dbo.SPAINPRICE.NEWSELL, 
dbo.SPAINPRICE.OLDRETAIL, dbo.SPAINPRICE.RETAIL, 
dbo.SPAINPRICE.COMMENT,dbo.XFBULLS.HCOMMENT, dbo.XFBULLS.COUNTRY, dbo.SPAINPRICE.IDNO, dbo.SPAINPRICE.STUD, dbo.XFBULLS.IBR, dbo.XFBULLS.LEU, 
dbo.XFBULLS.BT, dbo.XFBULLS.D, dbo.XFBULLS.BREED, dbo.XFBULLS.DOB, dbo.SPAINPRICE.INVENTORY, dbo.SPAINPRICE.EU_INVENTORY, dbo.SPAINPRICE.CODENO AS ITEM_KEY
FROM dbo.XFBULLS INNER JOIN dbo.SPAINPRICE ON dbo.XFBULLS.CODENO = dbo.SPAINPRICE.CODENO


GO

SET QUOTED_IDENTIFIER ON
GO

CREATE UNIQUE CLUSTERED INDEX [idx_XF_SPAINPRICE_VIEW_ITEM_KEY]
  ON [dbo].[XF_SPAINPRICE_VIEW] ([ITEM_KEY], [CODENO])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [idx_XF_SPAINPRICE_VIEW_CODENO]
  ON [dbo].[XF_SPAINPRICE_VIEW] ([CODENO])
  ON [PRIMARY]
GO