SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[Kristy_Internal_HPrice_View] as
select WWS.NEW, WWS.YS, BI.CODENO,  WWS.REGNAME, WWS.CODENAME, WWS.D,M.PTAM, HP.NEWCOST, HP.NEWSELL, CAST(((HP.NEWSELL - HP.NEWCOST)/HP.NEWSELL)*100 AS DECIMAL(4,1)) AS GP,
HP.RETAIL, HP.COMMENT, HP.COST500, HP.SELL500,CAST(((HP.SELL500-HP.COST500)/HP.SELL500)*100 AS DECIMAL(4,1)) AS GRID_GP,  WWS.HOUSED, BI.EC, WWS.DOB, WWS.UDT, 
BI2.EC AS X_EC
FROM BULLINDEX BI JOIN WWSBULLS WWS ON WWS.UID = BI.UID JOIN Megadairy M on M.UID = WWS.UID JOIN HPRICE HP ON HP.CODENO = BI.CODENO 
LEFT JOIN BULLINDEX BI2 ON BI.UID = BI2.UID AND 
BI2.STYPE = 'C' AND (BI2.ACTIVE = -1 OR BI2.LP = -1) AND BI2.CODENO NOT LIKE ('514%') 
GO