SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE 	VIEW [dbo].[MegadairyWWS] as
SELECT BI.ACTIVE, BI.DEL, BI.LP, BI.EC, BI.HCOMMENT, BI.QUAL, BI.CONC, BI.STYPE, M.NEW, M.BREED, M.COUNTRY, M.IDNO, BI.CODENO, M.REGNAME, M.D, M.RECESS, 
M.CODENAME, M.DOB, M.SOURCE, M.NDTRS, M.NHRDS, M.PTAM, M.PTAF_P, M.PTAF, M.PTAP_P, M.PTAP, M.REL_YLD, M.REL_MF, M.PREL, M.NM, M.REL_NM, M.PL, M.REL_PL, M.SCS, 
M.REL_SCS, M.MILK, M.FAT_P, M.FAT, M.PROTM, M.PRO_P, M.PRO, M.DPR, M.REL_DPR, M.DPR_DTRS, M.HCR, M.REL_HCR, M.HCR_DTRS, M.CCR, M.REL_CCR, M.CCR_DTRS, M.SAMPLE, 
M.STATUS, M.TPI, M.TDATE, M.TSOURCE, M.TDTRS, M.THRDS, M.PTAT, M.TREL, M.UDC, M.FLC, M.MOB, M.REL_MOB, M.BDC, M.DC, WWS.KC, WWS.BLG, WWS.BCN, WWS.IBR, WWS.LEU, 
WWS.BT, WWS.EHD, WWS.JOHNES, WWS.UDT, M.PEDIGREE, WWS.BLACK_PCT, M.IND, M.RELDATE, M.LDTRS, M.LHRDS, M.STAT, M.STR, M.BD, M.DF, M.RA, M.THURLW, M.RLS, M.RLR, 
M.FA, M.FLS, M.FUA, M.RUH, M.RUW, M.UC, M.UD, M.FTP, M.RTP, M.TEATL, M.CEDATE, M.CE_G_IND, M.SCE, M.PRELIM, M.SCE_OBS, M.SCE_REL, M.DCE, M.DCE_OBS, M.DCE_REL, 
M.SSB_OBS, M.SSB_HERDS, M.SSB_REL, M.SSB_PCT, M.SSB_SOURCE, M.SSB_OFF, M.DSB_OBS, M.DSB_DTRS, M.DSB_HERDS, M.DSB_REL, M.DSB_PCT, M.DSB_SOURCE, M.DSB_OFF, M.MS, 
M.REL_MS, M.DIS, WWS.AAA, WWS.DMS, 
CASE WHEN M.SERV_SCR = 0 THEN 'N/A' ELSE Format(M.SCR,'0.0') END AS SCR, 
CASE WHEN M.SERV_SCR = 0 THEN 'N/A' ELSE M.SERV_SCR END  AS SERV_SCR, 
CASE WHEN M.SERV_SCR = 0 THEN 'N/A' ELSE M.REL_SCR END AS REL_SCR, 
M.G_IND, M.EVALDATE, M.keyy, M.RHAIND, M.HBSTATUS, M.SBREED, M.SCOUNTRY, M.SIDNO, M.ALTREGNAME, M.SREGNAME, M.DBREED, M.DCOUNTRY, M.DIDNO,
M.DREGNAME, M.MGSBREED, M.MGSCOUNTRY, M.MGSIDNO, M.OBREED, M.OCOUNTRY, M.OIDNO, M.NAABCODE2, M.NAABCODE3, M.NAABCODE4, M.RUSSIA, M.Slovenia, M.S2, M.S3, M.S4, M.S5, 
M.S6, M.S7, M.S8, M.UKLIST, WWS.BIRTH_STATE, M.breed_eval, M.FTI, M.FUI, M.NM_PCTILE, M.QTYCNTRY, M.MDCNTRY, M.PCT_US, M.PA_MILK, M.PA_FAT, M.PA_PRO, 
M.REL_MF_PA, M.PA_PL, M.REL_PL_PA, M.PA_SCS, M.REL_SCS_PA, M.PA_DPR, M.REL_DPR_PA, M.PA_NM, M.REL_NM_PA,  M.INBRED_PCT, M.INBRED_DTR, 
M.INBRED_EFI, M.STUD, M.PA_HCR, M.REL_PA_HCR, M.PA_CCR, M.REL_PA_CCR, WWS.BREEDSORT, 
WWS.LOCATION, M.SAUDI, M.IRAN, M.RSA, M.ITALYLIST, M.AUSTRALIA, M.UID2, M.PKEY, M.TKEY, WWS.YS, M.NAABCODE5, M.NAABCODE6, M.ACE_SERV, M.ACE, M.ACE_STAR, 
M.CFI_SERV, M.CFI, M.ATA_SERV, M.ATA_SSFS, M.ATA_STAR, M.CHIPTYPE, M.INBRED_PCT_GEN, M.GFI, WWS.CLASS, M.FE, M.FI, WWS.SEXED_ONLY, LIV, SGL, SGL_REL
FROM (dbo.WWSBULLS WWS INNER JOIN dbo.BULLINDEX BI ON WWS.UID = BI.UID) INNER JOIN dbo.Megadairy M ON WWS.UID = M.UID
WHERE (BI.STYPE='C' and WWS.SEXED_ONLY = 0)  or (WWS.SEXED_ONLY = -1 AND BI.STYPE = 'X' AND BI.ACTIVE = -1);
GO