SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[WWS_Active_Lineup] AS
  SELECT
    MIN(BULLINDEX.CODENO) AS CODENO,
    WWSBULLS.UID,
    MIN(BULLINDEX.STYPE) AS STYPE,
    MIN(WWSBULLS.SEXED_ONLY) AS SEXED_ONLY
  FROM BULLINDEX
    INNER JOIN WWSBULLS
      ON BULLINDEX.UID = WWSBULLS.UID
  WHERE BULLINDEX.ACTIVE <> 0
  GROUP BY WWSBULLS.UID;
GO