SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WW_Indexes_Holstein]
AS
  SELECT DISTINCT
    WWSAL.Codeno AS CODENO,
    WWI.CODENAME,
    WWI.REGNAME,
    WWI.COUNTRY,
    WWI.BREED,
    WWI.IDNO,
    WWI.TREL,
    WWI.REL_MF,
    WWI.BALNDX,
    WWI.HIGHTYPENDX,
    WWI.HIPRONDX,
    WWI.COMPNDX,
    WWI.GRAZENDX,
    WWI.HEALTHNDX,
    WWI.EVALDATE,
    WWI.YS,
    WWI.UID
  FROM [dbo].[WW_Indexes] WWI
    INNER JOIN [dbo].[WWS_Active_Lineup] WWSAL
      ON WWI.UID = WWSAL.UID
GO