CREATE TABLE [dbo].[HaplotypeData] (
  [UID] [nvarchar](17) NOT NULL,
  [CODENO] [nvarchar](10) NULL,
  [REGNAME] [nvarchar](50) NULL,
  [HH0] [nvarchar](1) NULL,
  [HH1] [nvarchar](1) NULL,
  [HH2] [nvarchar](1) NULL,
  [HH3] [nvarchar](1) NULL,
  [HH4] [nvarchar](1) NULL,
  [HH5] [nvarchar](1) NULL,
  [HHB] [nvarchar](1) NULL,
  [HHC] [nvarchar](1) NULL,
  [HHD] [nvarchar](1) NULL,
  [HHM] [nvarchar](1) NULL,
  [HHP] [nvarchar](1) NULL,
  [HHR] [nvarchar](1) NULL,
  [HDR] [nvarchar](1) NULL,
  [HBR] [nvarchar](1) NULL,
  [HCD] [nvarchar](1) NULL,
  [JH1] [nvarchar](1) NULL,
  [JH1_PC] [nvarchar](1) NULL,
  [JH2] [nvarchar](1) NULL,
  [JH2_PC] [nvarchar](1) NULL,
  [JHP] [nvarchar](1) NULL,
  [JHP_PC] [nvarchar](1) NULL,
  [BH1] [nvarchar](1) NULL,
  [BH2] [nvarchar](1) NULL,
  [BHD] [nvarchar](1) NULL,
  [BHM] [nvarchar](1) NULL,
  [BHW] [nvarchar](1) NULL,
  [BHP] [nvarchar](1) NULL,
  [AH1] [nvarchar](1) NULL,
  PRIMARY KEY CLUSTERED ([UID])
)
ON [PRIMARY]
GO