CREATE TABLE [dbo].[BullsLocationMaster] (
  [CODENO] [nvarchar](10) NOT NULL,
  [MKTG_CODENO] [nvarchar](10) NOT NULL,
  [REGNAME] [nvarchar](50) NULL,
  [CODENAME] [nvarchar](50) NULL,
  [COUNTRY] [nvarchar](3) NULL,
  [IDNO] [nvarchar](12) NULL,
  [DOB] [datetime] NULL,
  [RESIDENCY_DATE] [datetime] NULL,
  [OWN_LEASE] [nvarchar](1) NULL,
  [MOVE_DATE] [datetime] NULL,
  [STATE] [nvarchar](5) NULL,
  [FAC] [nvarchar](5) NULL,
  [BARN] [nvarchar](10) NULL,
  [DEAD] [nvarchar](1) NULL,
  [BARN_KEY] [nvarchar](30) NULL,
  [BREED] [nvarchar](2) NULL,
  [BEEF_DAIRY] [nvarchar](1) NULL,
  [ITEM_KEY] [nvarchar](10) NULL,
  [UID] [nvarchar](17) NULL,
  [SUPPLIER] [nvarchar](2) NULL,
  [Inventory_Flag] [nvarchar](1) NULL,
  [EU_Inventory_Flag] [nvarchar](1) NULL,
  [Current_Inv] [int] NULL,
  [Current_EU_Inv] [int] NULL,
  [UDT] [nvarchar](5) NULL,
  [inv_update_datetime] [datetime] NULL,
  [Prev_Barn_Key] [nvarchar](30) NULL,
  [Prev_Barn_Description] [nvarchar](255) NULL,
  [Prev_Move_Date] [datetime] NULL,
  [Prev_Inv_Flag] [nvarchar](1) NULL,
  [Prev_EU_Inv_Flag] [nvarchar](1) NULL,
  PRIMARY KEY CLUSTERED ([CODENO], [MKTG_CODENO])
)
ON [PRIMARY]
GO