CREATE TABLE [dbo].[MACETYPE] (
  [UID] [varchar](17) NOT NULL,
  [COUNTRY] [varchar](3) NULL,
  [SEX] [varchar](1) NULL,
  [IDNO] [varchar](12) NULL,
  [CODENO] [varchar](10) NULL,
  [TREL] [smallint] NULL,
  [TREL_US] [smallint] NULL,
  [TDTRS] [int] NULL,
  [THRDS] [int] NULL,
  [PTAT] [real] NULL,
  [LREL] [smallint] NULL,
  [LDTRS] [int] NULL,
  [LHRDS] [int] NULL,
  [LEFFDTRS] [smallint] NULL,
  [REL_RLS] [smallint] NULL,
  [REL_FLS] [smallint] NULL,
  [REL_RTP] [smallint] NULL,
  [STAT] [real] NULL,
  [STR] [real] NULL,
  [BD] [real] NULL,
  [DF] [real] NULL,
  [RA] [real] NULL,
  [THURLW] [real] NULL,
  [RLS] [real] NULL,
  [RLR] [real] NULL,
  [FA] [real] NULL,
  [FLS] [real] NULL,
  [FUA] [real] NULL,
  [RUH] [real] NULL,
  [RUW] [real] NULL,
  [UC] [real] NULL,
  [UD] [real] NULL,
  [FTP] [real] NULL,
  [RTP] [real] NULL,
  [TEATL] [real] NULL,
  [UDC] [real] NULL,
  [FLC] [real] NULL,
  [BDC] [real] NULL,
  [DC] [real] NULL,
  [US_PCT] [smallint] NULL,
  [CNTRY_MD] [varchar](3) NULL,
  [QTYCNTRY] [smallint] NULL,
  [TSOURCE] [varchar](10) NULL,
  [ICNTRY] [varchar](3) NULL,
  [ISEX] [varchar](1) NULL,
  [IIDNO] [varchar](12) NULL,
  [HBSTATUS] [varchar](3) NULL,
  [RHAIND] [varchar](2) NULL,
  [REGNAME] [varchar](30) NULL,
  [DOB] [varchar](10) NULL,
  [BREED] [varchar](2) NULL,
  [TKEY] [varchar](1) NULL,
  [TDATE] [date] NULL,
  [SSMA_TIMESTAMP] [timestamp],
  CONSTRAINT [pk_mtype_UID] PRIMARY KEY CLUSTERED ([UID])
)
ON [PRIMARY]
GO