CREATE TABLE [dbo].[NAABSTAT_in] (
  [SEX] [nvarchar](1) NULL,
  [BREED] [nvarchar](2) NULL,
  [COUNTRY] [nvarchar](3) NULL,
  [IDNO] [nvarchar](12) NULL,
  [F1] [nvarchar](1) NULL,
  [CTRLR] [nvarchar](4) NULL,
  [F2] [nvarchar](1) NULL,
  [CODENO] [nvarchar](10) NULL,
  [F3] [nvarchar](1) NULL,
  [CODENAME] [nvarchar](20) NULL,
  [F4] [nvarchar](1) NULL,
  [SCE] [nvarchar](4) NULL,
  [F5] [nvarchar](1) NULL,
  [SCE_REL] [nvarchar](2) NULL,
  [F6] [nvarchar](1) NULL,
  [SCE_OBS] [nvarchar](5) NULL,
  [F7] [nvarchar](1) NULL,
  [DCE] [nvarchar](4) NULL,
  [F8] [nvarchar](1) NULL,
  [DCE_REL] [nvarchar](2) NULL,
  [F9] [nvarchar](1) NULL,
  [DCE_OBS] [nvarchar](7) NULL,
  [SAMPLE] [nvarchar](1) NULL,
  [F10] [nvarchar](1) NULL,
  [AAA] [nvarchar](6) NULL,
  [F11] [nvarchar](2) NULL,
  [DMS] [nvarchar](7) NULL,
  [F12] [nvarchar](1) NULL,
  [PRICE] [nvarchar](3) NULL,
  [F13] [nvarchar](1) NULL,
  [STATUS] [nvarchar](1) NULL
)
ON [PRIMARY]
GO