CREATE TABLE [dbo].[TYPE] (
  [COUNTRY] [nvarchar](3) NULL,
  [BREED] [nvarchar](2) NULL,
  [IDNO] [nvarchar](12) NULL,
  [HBSTATUS] [nvarchar](3) NULL,
  [RHAIND] [nvarchar](2) NULL,
  [REGNAME] [nvarchar](30) NULL,
  [RECESS] [nvarchar](16) NULL,
  [SCOUNTRY] [nvarchar](3) NULL,
  [SBREED] [nvarchar](2) NULL,
  [SIDNO] [nvarchar](12) NULL,
  [SHBSTATUS] [nvarchar](3) NULL,
  [SRHAIND] [nvarchar](2) NULL,
  [SREGNAME] [nvarchar](30) NULL,
  [SRECESS] [nvarchar](16) NULL,
  [DCOUNTRY] [nvarchar](3) NULL,
  [DBREED] [nvarchar](2) NULL,
  [DIDNO] [nvarchar](12) NULL,
  [DHBSTATUS] [nvarchar](3) NULL,
  [DRHAIND] [nvarchar](2) NULL,
  [DREGNAME] [nvarchar](30) NULL,
  [DRECESS] [nvarchar](16) NULL,
  [DOB] [date] NULL,
  [CODENO] [nvarchar](10) NULL,
  [STATUS] [nvarchar](1) NULL,
  [DATEPTAT] [nvarchar](6) NULL,
  [STAPTAT] [real] NULL,
  [PTAT] [real] NULL,
  [TREL] [smallint] NULL,
  [TRECORDS] [int] NULL,
  [TDTRS] [int] NULL,
  [TGRDDTRS] [int] NULL,
  [THRDS] [int] NULL,
  [THRD_CLASS] [int] NULL,
  [EFF_DTRS] [real] NULL,
  [AFSCDTRS] [real] NULL,
  [AASCDTRS] [real] NULL,
  [SDAASC] [real] NULL,
  [NSTATES] [nvarchar](2) NULL,
  [NYRS] [nvarchar](2) NULL,
  [INDICATOR] [nvarchar](1) NULL,
  [DATELIN] [nvarchar](6) NULL,
  [LREL] [smallint] NULL,
  [LRECORDS] [int] NULL,
  [LDTRS] [int] NULL,
  [LHRDS] [int] NULL,
  [LHRD_CLASS] [int] NULL,
  [LEFFDTRS] [real] NULL,
  [STAT] [real] NULL,
  [DA_STAT] [nvarchar](4) NULL,
  [SD_STAT] [nvarchar](4) NULL,
  [STR] [real] NULL,
  [DA_STR] [nvarchar](4) NULL,
  [SD_STR] [nvarchar](4) NULL,
  [BD] [real] NULL,
  [DA_BD] [nvarchar](4) NULL,
  [SD_BD] [nvarchar](4) NULL,
  [DF] [real] NULL,
  [DA_DF] [nvarchar](4) NULL,
  [SD_DF] [nvarchar](4) NULL,
  [RA] [real] NULL,
  [DA_RA] [nvarchar](4) NULL,
  [SD_RA] [nvarchar](4) NULL,
  [THURLW] [real] NULL,
  [DA_THURLW] [nvarchar](4) NULL,
  [SD_THURLW] [nvarchar](4) NULL,
  [RLS] [real] NULL,
  [DA_RLS] [nvarchar](4) NULL,
  [SD_RLS] [nvarchar](4) NULL,
  [RLR] [real] NULL,
  [DA_RLR] [nvarchar](4) NULL,
  [SD_RLR] [nvarchar](4) NULL,
  [FA] [real] NULL,
  [DA_FA] [nvarchar](4) NULL,
  [SD_FA] [nvarchar](4) NULL,
  [FLS] [real] NULL,
  [DA_FLS] [nvarchar](4) NULL,
  [SD_FLS] [nvarchar](4) NULL,
  [FUA] [real] NULL,
  [DA_FUA] [nvarchar](4) NULL,
  [SD_FUA] [nvarchar](4) NULL,
  [RUH] [real] NULL,
  [DA_RUH] [nvarchar](4) NULL,
  [SD_RUH] [nvarchar](4) NULL,
  [RUW] [real] NULL,
  [DA_RUW] [nvarchar](4) NULL,
  [SD_RUW] [nvarchar](4) NULL,
  [UC] [real] NULL,
  [DA_UC] [nvarchar](4) NULL,
  [SD_UC] [nvarchar](4) NULL,
  [UD] [real] NULL,
  [DA_UD] [nvarchar](4) NULL,
  [SD_UD] [nvarchar](4) NULL,
  [FTP] [real] NULL,
  [DA_FTP] [nvarchar](4) NULL,
  [SD_FTP] [nvarchar](4) NULL,
  [RTP] [real] NULL,
  [DA_RTP] [nvarchar](4) NULL,
  [SD_RTP] [nvarchar](4) NULL,
  [TEATL] [real] NULL,
  [DA_TEATL] [nvarchar](4) NULL,
  [SD_TEATL] [nvarchar](4) NULL,
  [UDC] [real] NULL,
  [FLC] [real] NULL,
  [BDC] [real] NULL,
  [DC] [real] NULL,
  [MOB] [real] NULL,
  [REL_MOB] [smallint] NULL,
  [MOB_HRDS] [int] NULL,
  [MOB_DTRS] [int] NULL,
  [TREL_US] [smallint] NULL,
  [TSOURCE] [nvarchar](4) NULL,
  [TKEY] [nvarchar](1) NULL,
  [TDATE] [date] NULL,
  [FTI] [real] NULL,
  [FUI] [real] NULL,
  [UID] [nvarchar](17) NULL,
  [RTPS] [real] NULL,
  [REL_RTPS] [smallint] NULL
)
ON [PRIMARY]
GO

CREATE INDEX [idx_TYPE_IDNO]
  ON [dbo].[TYPE] ([UID])
  ON [PRIMARY]
GO

CREATE INDEX [idx_TYPE_REGNAME]
  ON [dbo].[TYPE] ([REGNAME])
  ON [PRIMARY]
GO

CREATE UNIQUE CLUSTERED INDEX [idx_TYPE_UID]
  ON [dbo].[TYPE] ([UID])
  ON [PRIMARY]
GO