CREATE TABLE [dbo].[MARSXDPRICE_HISTORY] (
  [PROOF_PERIOD] [nvarchar](10) NOT NULL,
  [CODENO] [nvarchar](10) NOT NULL,
  [ACTIVE] [int] NULL DEFAULT (0),
  [LP] [int] NULL DEFAULT (0),
  [YS] [nvarchar](1) NULL,
  [INACTIVE] [nvarchar](3) NULL,
  [CODENAME] [nvarchar](20) NULL,
  [REGNAME] [nvarchar](33) NULL,
  [OLDCOST] [float] NULL,
  [NEWCOST] [float] NULL,
  [DECREASE] [nvarchar](1) NULL,
  [OLDSELL] [float] NULL,
  [NEWSELL] [float] NULL,
  [OLDRETAIL] [float] NULL,
  [RETAIL] [float] NULL,
  [MINCOST] [float] NULL,
  [MINSELL] [float] NULL,
  [COST500] [float] NULL,
  [SELL500] [float] NULL,
  [COMMENT] [nvarchar](50) NULL,
  [INVENTORY] [int] NULL,
  [EU_INVENTORY] [int] NULL,
  [ROYALTY] [nvarchar](20) NULL,
  [NEW] [nvarchar](3) NULL DEFAULT (NULL),
  [HOUSED] [nvarchar](10) NULL DEFAULT (NULL),
  [IDNO] [nvarchar](12) NULL DEFAULT (NULL),
  [STUD] [int] NULL DEFAULT (202),
  [UID] [nvarchar](17) NULL DEFAULT (NULL),
  [STYPE] [nvarchar](1) NULL DEFAULT (NULL),
  [BREED] [nvarchar](2) NULL DEFAULT (NULL),
  PRIMARY KEY CLUSTERED ([PROOF_PERIOD], [CODENO])
)
ON [PRIMARY]
GO