CREATE TABLE [dbo].[38ID_IN] (
  [SPECIES] [nvarchar](1) NULL,
  [BREED_EVAL] [nvarchar](2) NULL,
  [BREED] [nvarchar](2) NULL,
  [COUNTRY] [nvarchar](3) NULL,
  [IDNO] [nvarchar](12) NULL,
  [SBREED] [nvarchar](2) NULL,
  [SCOUNTRY] [nvarchar](3) NULL,
  [SIDNO] [nvarchar](12) NULL,
  [DBREED] [nvarchar](2) NULL,
  [DCOUNTRY] [nvarchar](3) NULL,
  [DIDNO] [nvarchar](12) NULL,
  [MGSBREED] [nvarchar](2) NULL,
  [MGSCOUNTRY] [nvarchar](3) NULL,
  [MGSIDNO] [nvarchar](12) NULL,
  [OBREED] [nvarchar](2) NULL,
  [OCOUNTRY] [nvarchar](3) NULL,
  [OIDNO] [nvarchar](12) NULL,
  [DOB] [nvarchar](8) NULL,
  [HBSTATUS] [nvarchar](2) NULL,
  [REGNAME] [nvarchar](30) NULL,
  [CODENAME] [nvarchar](20) NULL,
  [AIDATE] [nvarchar](6) NULL,
  [SAMPLE] [nvarchar](1) NULL,
  [SCTRL] [nvarchar](4) NULL,
  [STATUS] [nvarchar](1) NULL,
  [STUD] [nvarchar](4) NULL,
  [QTYCODES] [nvarchar](1) NULL,
  [CODENO] [nvarchar](10) NULL,
  [NAABCODE2] [nvarchar](10) NULL,
  [NAABCODE3] [nvarchar](10) NULL,
  [NAABCODE4] [nvarchar](10) NULL,
  [MGDBREED] [nvarchar](2) NULL,
  [MGDCOUNTRY] [nvarchar](3) NULL,
  [MGDIDNO] [nvarchar](12) NULL,
  [MGDSBREED] [nvarchar](2) NULL,
  [MGDSCOUNTRY] [nvarchar](3) NULL,
  [MGDSIDNO] [nvarchar](12) NULL
)
ON [PRIMARY]
GO