CREATE TABLE [dbo].[CE] (
  [BREED_EVAL] [nvarchar](2) NULL,
  [BREED] [nvarchar](2) NULL,
  [COUNTRY] [nvarchar](3) NULL,
  [IDNO] [nvarchar](12) NULL,
  [G_IND] [nvarchar](1) NULL,
  [CODENO] [nvarchar](10) NULL,
  [CODENAME] [nvarchar](20) NULL,
  [STUD] [int] NULL,
  [SCE_OBS] [int] NULL,
  [SCE_HERDS] [int] NULL,
  [SCE_REL] [int] NULL,
  [SCE_USOL] [real] NULL,
  [SCE] [real] NULL,
  [PRELIM] [nvarchar](1) NULL,
  [SCE_DOM_PCT] [smallint] NULL,
  [MOST_SCE_CNTRY] [nvarchar](3) NULL,
  [SCE_QTY_CNTRY] [smallint] NULL,
  [SCE_SOURCE] [nvarchar](4) NULL,
  [SCE_OFF] [nvarchar](1) NULL,
  [DCE_OBS] [int] NULL,
  [DCE_DTRS] [int] NULL,
  [DCE_HERDS] [int] NULL,
  [DCE_REL] [smallint] NULL,
  [DCE_USOL] [real] NULL,
  [DCE] [real] NULL,
  [DCE_DOM_PCT] [smallint] NULL,
  [MOST_DTR_CNTRY] [nvarchar](3) NULL,
  [DCE_QTY_CNTRY] [smallint] NULL,
  [DCE_SOURCE] [nvarchar](4) NULL,
  [DCE_OFF] [nvarchar](1) NULL,
  [SSB_OBS] [int] NULL,
  [SSB_HERDS] [int] NULL,
  [SSB_REL] [smallint] NULL,
  [SSB_USOL] [real] NULL,
  [SSB_PCT] [real] NULL,
  [SSB_DOM_PCT] [smallint] NULL,
  [MOST_SSB_CNTRY] [nvarchar](3) NULL,
  [SSB_QTY_CNTRY] [smallint] NULL,
  [SSB_SOURCE] [nvarchar](1) NULL,
  [SSB_OFF] [nvarchar](1) NULL,
  [DSB_OBS] [int] NULL,
  [DSB_DTRS] [int] NULL,
  [DSB_HERDS] [int] NULL,
  [DSB_REL] [smallint] NULL,
  [DSB_USOL] [real] NULL,
  [DSB_PCT] [real] NULL,
  [DSB_DOM_PCT] [smallint] NULL,
  [MOST_DSB_CNTRY] [nvarchar](3) NULL,
  [DSB_QTY_CNTRY] [smallint] NULL,
  [DSB_SOURCE] [nvarchar](1) NULL,
  [DSB_OFF] [nvarchar](1) NULL,
  [UID] [nvarchar](17) NOT NULL,
  [CEDATE] [date] NULL,
  [SSMA_TIMESTAMP] [timestamp],
  CONSTRAINT [CE$PrimaryKey] PRIMARY KEY CLUSTERED ([UID])
)
ON [PRIMARY]
GO