CREATE TABLE [dbo].[Optifeed] (
  [UID] [nvarchar](255) NULL,
  [CODENAME] [nvarchar](255) NULL,
  [REGNAME] [nvarchar](255) NULL,
  [CODENO] [nvarchar](255) NULL,
  [ACTIVE] [float] NULL,
  [YS] [nvarchar](255) NULL,
  [Opti_SCORE] [float] NULL,
  [PTAM] [float] NULL,
  [PTAF] [float] NULL,
  [PTAF_P] [float] NULL,
  [PTAP] [float] NULL,
  [PTAP_P] [float] NULL,
  [REL_YLD] [float] NULL,
  [PTAP1] [float] NULL,
  [UDC] [float] NULL,
  [FLC] [float] NULL,
  [TREL] [float] NULL,
  [SCE] [float] NULL,
  [DCE] [float] NULL,
  [SCS] [float] NULL,
  [PL] [float] NULL,
  [DPR] [float] NULL,
  [TPI] [float] NULL,
  [DSB_PCT] [nvarchar](255) NULL,
  [DC] [nvarchar](255) NULL,
  [BDC] [nvarchar](255) NULL,
  [BD] [float] NULL,
  [STAT] [float] NULL,
  [STR] [float] NULL,
  [DF] [float] NULL,
  [RA] [float] NULL,
  [THURLW] [float] NULL,
  [RLR] [float] NULL,
  [FA] [float] NULL,
  [FUA] [float] NULL,
  [RUH] [float] NULL,
  [RUW] [float] NULL,
  [UC] [float] NULL,
  [UD] [float] NULL,
  [FTP] [float] NULL,
  [TEATL] [float] NULL
)
ON [PRIMARY]
GO