CREATE TABLE [dbo].[MARBULLS] (
  [YS] [nvarchar](1) NULL,
  [NEW] [nvarchar](1) NULL,
  [REGNAME] [nvarchar](45) NULL,
  [DEU_IDNO] [float] NULL,
  [RECESS] [nvarchar](17) NULL,
  [D] [nvarchar](1) NULL,
  [CODENAME] [nvarchar](20) NULL,
  [CODENO] [nvarchar](10) NULL,
  [BREED] [nvarchar](2) NULL,
  [STUD] [float] NULL,
  [LOCATION] [float] NULL,
  [COUNTRY] [nvarchar](3) NULL,
  [IDNO] [nvarchar](12) NULL,
  [DOB] [date] NULL,
  [MS] [float] NULL,
  [DIS] [float] NULL,
  [KC] [nvarchar](2) NULL,
  [BLG] [nvarchar](2) NULL,
  [BCN] [nvarchar](5) NULL,
  [IBR] [nvarchar](4) NULL,
  [LEU] [nvarchar](3) NULL,
  [BT] [nvarchar](3) NULL,
  [QUALIFIED] [int] NULL,
  [SPECIAL] [nvarchar](1) NULL,
  [HCOMMENT] [nvarchar](20) NULL,
  [SELL_PRICE] [float] NULL,
  [PEDIGREE] [nvarchar](30) NULL,
  [SIRE] [nvarchar](31) NULL,
  [SRV] [int] NULL,
  [FAX] [int] NULL,
  [S] [int] NULL,
  [SCODENO] [nvarchar](10) NULL,
  [MGSIDNO] [nvarchar](12) NULL,
  [KEY] [nvarchar](1) NULL,
  [CK] [int] NULL,
  [SBREED] [nvarchar](2) NULL,
  [SCOUNTRY] [nvarchar](3) NULL,
  [SIDNO] [nvarchar](12) NULL,
  [BREEDSORT] [nvarchar](2) NULL,
  [SREGNO] [nvarchar](12) NULL,
  [aAa] [nvarchar](6) NULL,
  [LP] [int] NULL,
  [HOUSED] [nvarchar](10) NULL,
  [UID] [nvarchar](17) NULL,
  [SEXED_ONLY] [int] NOT NULL DEFAULT (0),
  [Megadairy_UID] [varchar](17) NULL DEFAULT (NULL)
)
ON [PRIMARY]
GO

CREATE UNIQUE CLUSTERED INDEX [idx_MARBULLS_UID]
  ON [dbo].[MARBULLS] ([UID])
  ON [PRIMARY]
GO