CREATE TABLE [dbo].[38Pedigree_20170124] (
  [SPECIES] [nvarchar](1) NULL,
  [BREED_EVAL] [nvarchar](2) NULL,
  [REG-ID] [nvarchar](17) NOT NULL,
  [BREED] [nvarchar](2) NULL,
  [COUNTRY] [nvarchar](3) NULL,
  [IDNO] [nvarchar](12) NULL,
  [SBREED] [nvarchar](2) NULL,
  [SCOUNTRY] [nvarchar](3) NULL,
  [SIDNO] [nvarchar](12) NULL,
  [SREGNAME] [nvarchar](50) NULL,
  [SCODENAME] [nvarchar](20) NULL,
  [SCODENO] [nvarchar](10) NULL,
  [SUID] [nvarchar](17) NULL,
  [DBREED] [nvarchar](2) NULL,
  [DCOUNTRY] [nvarchar](3) NULL,
  [DIDNO] [nvarchar](12) NULL,
  [DREGNAME] [nvarchar](30) NULL,
  [DUID] [nvarchar](17) NULL,
  [MGSBREED] [nvarchar](2) NULL,
  [MGSCOUNTRY] [nvarchar](3) NULL,
  [MGSIDNO] [nvarchar](12) NULL,
  [MGSREGNAME] [nvarchar](50) NULL,
  [MGSCODENAME] [nvarchar](20) NULL,
  [MGSCODENO] [nvarchar](10) NULL,
  [MGSUID] [nvarchar](17) NULL,
  [OBREED] [nvarchar](2) NULL,
  [OCOUNTRY] [nvarchar](3) NULL,
  [OIDNO] [nvarchar](12) NULL,
  [DOB] [datetime2] NULL,
  [HBSTATUS] [nvarchar](2) NULL,
  [REGNAME] [nvarchar](50) NULL,
  [CODENAME] [nvarchar](20) NULL,
  [AIDATE] [nvarchar](6) NULL,
  [SAMPLE] [nvarchar](1) NULL,
  [SCTRL] [nvarchar](4) NULL,
  [STATUS] [nvarchar](1) NULL,
  [STUD] [nvarchar](4) NULL,
  [QTYCODES] [nvarchar](1) NULL,
  [CODENO] [nvarchar](10) NULL,
  [NAABCODE2] [nvarchar](10) NULL,
  [NAABCODE3] [nvarchar](10) NULL,
  [NAABCODE4] [nvarchar](10) NULL,
  [MGDBREED] [nvarchar](2) NULL,
  [MGDCOUNTRY] [nvarchar](3) NULL,
  [MGDIDNO] [nvarchar](12) NULL,
  [MGDREGNAME] [nvarchar](50) NULL,
  [MKTG_PEDIGREE] [nvarchar](66) NULL,
  [PEDIGREE] [nvarchar](66) NULL,
  [PGSBREED] [nvarchar](2) NULL,
  [PGSCOUNTRY] [nvarchar](3) NULL,
  [PGSIDNO] [nvarchar](12) NULL,
  [PGSREGNAME] [nvarchar](50) NULL,
  [PGSCODENO] [nvarchar](50) NULL,
  [PGSCODENAME] [nvarchar](20) NULL,
  [PGSUID] [nvarchar](50) NULL,
  [MGGSBREED] [nvarchar](2) NULL,
  [MGGSCOUNTRY] [nvarchar](3) NULL,
  [MGGSIDNO] [nvarchar](12) NULL,
  [MGGSREGNAME] [nvarchar](50) NULL,
  [MGGSCODENAME] [nvarchar](25) NULL,
  [MGGSCODENO] [nvarchar](10) NULL,
  [MGGSUID] [nvarchar](17) NULL,
  [UID] [nvarchar](17) NOT NULL,
  [ID] [int] NULL,
  [created_date] [date] NULL,
  [last_update_date] [date] NULL,
  CONSTRAINT [pk_Ped38_UID_20170124] PRIMARY KEY CLUSTERED ([UID])
)
ON [PRIMARY]
GO